#!/usr/bin/env node
// Generates lib/Suflet/src/EyeTables.h from the founder-approved web engine
// (../eyes/eyes.js) and the collection (../eyes/designs.json), so the C++ port
// uses exactly the same numbers: every design, every mood/reaction timeline,
// the spring constants and the 15 s demo script.
//
//   node tools/gen_eyes.js            (run from firmware/)
//
// eyes.js is not modified: its source is evaluated with a few internals
// (BASE, SCRIPT, springFor, expand) added to the returned object.
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const eyesDir = path.resolve(root, '..', 'eyes');
const src = fs.readFileSync(path.join(eyesDir, 'eyes.js'), 'utf8');
const marker = 'return {\n    VERSION,';
if (!src.includes(marker)) throw new Error('eyes.js layout changed: cannot find the export object');
const patched = src.replace(marker, 'return {\n    __BASE: BASE, __SCRIPT: SCRIPT, __springFor: springFor, __expand: expand, __EYE_KEYS: EYE_KEYS,\n    VERSION,');
const mod = { exports: {} };
new Function('module', 'exports', 'self', patched)(mod, mod.exports, undefined);
const E = mod.exports;
const designsDoc = JSON.parse(fs.readFileSync(path.join(eyesDir, 'designs.json'), 'utf8'));
const designs = designsDoc.designs;

const CH = Object.keys(E.__BASE);
const chIndex = (k) => {
  const i = CH.indexOf(k);
  if (i < 0) throw new Error('unknown channel ' + k);
  return i;
};
const SHAPES = ['egg', 'squircle', 'almond', 'drop', 'crescent'];
const PUPILS = ['round', 'slit', 'plus', 'star', 'heart', 'ring', 'double', 'pebble', 'crescent', 'diamond', 'spiral', 'battery', 'level'];
const GMODES = ['idle', 'still', 'spin', 'rattle', 'sway', 'drift', 'wobble', 'scan'];
const FX = ['shimmer', 'rainbow', 'chrome', 'aurora', 'starfield', 'folk', 'glitter', 'outline', 'galaxy', 'halo'];
const RAR = E.RARITIES.map((r) => r.key);

const f = (v) => {
  if (!Number.isFinite(v)) throw new Error('bad number ' + v);
  let s = String(+v.toPrecision(9));
  if (!/[.e]/.test(s)) s += '.0';
  return s + 'f';
};
const d = (v) => {
  let s = String(v);
  if (!/[.e]/.test(s)) s += '.0';
  return s;
};
const hex = (h) => {
  h = String(h).replace('#', '');
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  return '0x' + h.slice(0, 6).toUpperCase();
};
const cstr = (s) => JSON.stringify(String(s)).replace(/[\u0080-￿]/g, (c) =>
  Buffer.from(c, 'utf8').reduce((a, b) => a + '\\x' + b.toString(16).padStart(2, '0') + '""', ''));

let out = [];
const w = (s) => out.push(s);
w('// GENERATED by tools/gen_eyes.js from ../eyes/eyes.js v' + E.VERSION + ' and ../eyes/designs.json.');
w('// Do not edit by hand: change the web engine / the collection and re-run the generator.');
w('#pragma once');
w('#include <stdint.h>');
w('');
w('namespace suflet {');
w('namespace eyes {');
w('');
w('// ---- rig channels (eyes.js BASE, same order) ----');
w('enum Ch : uint8_t {');
CH.forEach((k, i) => w(`  Ch_${k} = ${i},`));
w(`  Ch_Count = ${CH.length}`);
w('};');
w(`static constexpr float kBase[Ch_Count] = {${CH.map((k) => f(E.__BASE[k])).join(', ')}};`);
w(`static constexpr float kSpringK[Ch_Count] = {${CH.map((k) => f(E.__springFor(k)[0])).join(', ')}};`);
w(`static constexpr float kSpringZ[Ch_Count] = {${CH.map((k) => f(E.__springFor(k)[1])).join(', ')}};`);
w(`static const char* const kChNames[Ch_Count] = {${CH.map((k) => cstr(k)).join(', ')}};`);
w('');
w(`enum class Shape : uint8_t { ${SHAPES.map((s) => s[0].toUpperCase() + s.slice(1)).join(', ')} };`);
w(`enum class Pupil : uint8_t { ${PUPILS.map((s) => s[0].toUpperCase() + s.slice(1)).join(', ')}, None = 255 };`);
w(`enum class GazeMode : uint8_t { ${GMODES.map((s) => s[0].toUpperCase() + s.slice(1)).join(', ')}, Keep = 255 };`);
w('namespace fx {');
FX.forEach((x, i) => w(`constexpr uint16_t ${x[0].toUpperCase() + x.slice(1)} = 1u << ${i};`));
w('}  // namespace fx');
w(`enum class Rarity : uint8_t { ${RAR.map((s) => s[0].toUpperCase() + s.slice(1)).join(', ')}, Count };`);
w(`static constexpr double kRarityRate[] = {${E.RARITIES.map((r) => d(r.rate)).join(', ')}};`);
w(`static const char* const kRarityName[] = {${E.RARITIES.map((r) => cstr(r.name)).join(', ')}};`);
w(`static constexpr uint32_t kRarityColor[] = {${E.RARITIES.map((r) => hex(r.color)).join(', ')}};`);
w('');

// ---- designs ----
w('struct Design {');
w('  const char* id;');
w('  const char* name;');
w('  uint16_t num;');
w('  Rarity rarity;');
w('  Shape shape;');
w('  float rx, ry, spacing, y, egg, lean, n, q, flick, dip;');
w('  uint32_t white, whiteR;');
w('  Pupil pupil;');
w('  uint32_t pupilL, pupilR;');
w('  float prx, pry, inset, travel;');
w('  bool glint;');
w('  uint32_t glintColor;');
w('  float glintSize;');
w('  uint16_t fx;');
w('  float hue;');
w('  uint32_t aurora[4];');
w('  uint8_t nAurora;');
w('  uint32_t folkBase, folkThread, glitter, halo;');
w('};');
w('');
w(`static const Design kDesigns[${designs.length}] = {`);
for (const raw of designs) {
  const x = E.normalizeDesign(raw);
  const S = x.shape, P = x.pupil;
  if (!SHAPES.includes(S.type || 'egg')) throw new Error('shape ' + S.type);
  if (!PUPILS.includes(P.type)) throw new Error('pupil ' + P.type);
  let fxm = [];
  for (const k of x.fx || []) {
    if (!FX.includes(k)) throw new Error('fx ' + k);
    fxm.push('fx::' + k[0].toUpperCase() + k.slice(1));
  }
  const au = (x.auroraColors || ['#5CFFB0', '#3FD9FF', '#B07BFF']).slice(0, 4);
  const nAu = au.length;
  while (au.length < 4) au.push(au[au.length - 1]);
  const sh = (S.type || 'egg');
  w(`  {${cstr(x.id)}, ${cstr(x.name)}, ${x.n | 0}, Rarity::${x.rarity[0].toUpperCase() + x.rarity.slice(1)}, Shape::${sh[0].toUpperCase() + sh.slice(1)},`);
  w(`   ${f(S.rx)}, ${f(S.ry)}, ${f(S.spacing)}, ${f(S.y)}, ${f(S.egg || 0)}, ${f(S.lean || 0)}, ${f(S.n || 3.4)}, ${f(S.q == null ? 0.5 : S.q)}, ${f(S.flick || 0.18)}, ${f(S.dip || 0.5)},`);
  w(`   ${hex(x.white)}, ${hex(x.whiteR || x.white)}, Pupil::${P.type[0].toUpperCase() + P.type.slice(1)}, ${hex(P.L)}, ${hex(P.R || P.L)},`);
  w(`   ${f(P.rx)}, ${f(P.ry)}, ${f(P.inset)}, ${f(P.travel)}, ${x.glint ? 'true' : 'false'}, ${hex((x.glint && x.glint.color) || '#FFF6E2')}, ${f((x.glint && x.glint.size) || 1)},`);
  w(`   ${fxm.length ? fxm.join(' | ') : '0'}, ${f(x.hue || 0)}, {${au.map(hex).join(', ')}}, ${nAu},`);
  w(`   ${hex(x.folkBase || '#FFF6E6')}, ${hex(x.folkThread || '#141414')}, ${hex(x.glitterColor || '#FFFFFF')}, ${hex(x.haloColor || '#FFD23A')}},`);
}
w('};');
w(`static constexpr int kDesignCount = ${designs.length};`);
w('');

// ---- expressions ----
w('struct KV {');
w('  uint8_t ch;');
w('  float v;');
w('};');
w('struct Key {');
w('  float t;');
w('  const KV* snap;');
w('  uint8_t nSnap;');
w('  const KV* set;');
w('  uint8_t nSet;');
w('  const KV* kick;');
w('  uint8_t nKick;');
w('  Pupil alt;        // None = keep');
w('  bool hasGaze;');
w('  float gx, gy;');
w('  GazeMode mode;    // Keep = keep');
w('  float shakeF;     // 0 = keep');
w('  uint8_t blink;    // 0 = none');
w('};');
w('struct MoodDef {');
w('  const char* name;');
w('  const char* label;');
w('  float targets[Ch_Count];  // BASE merged with the mood set (eyes.js go())');
w('  const KV* kick;');
w('  uint8_t nKick;');
w('  float anticD;             // 0 = no anticipation');
w('  const KV* antic;');
w('  uint8_t nAntic;');
w('  bool anticHasGaze;');
w('  float anticGx, anticGy;');
w('  float gx, gy;             // base gaze');
w('  GazeMode mode;');
w('  Pupil alt;                // None = keep');
w('  float shakeF;             // 20 when the mood has none');
w('  float blinkSlow, blinkEvery;');
w('  uint8_t blink;');
w('  const Key* keys;');
w('  uint8_t nKeys;');
w('};');
w('struct ReactionDef {');
w('  const char* name;');
w('  const char* label;');
w('  float dur;');
w('  const Key* keys;');
w('  uint8_t nKeys;');
w('};');
w('');

let uid = 0;
const kvArr = (obj) => {
  if (!obj) return ['nullptr', 0];
  const e = E.__expand(obj);
  const ks = Object.keys(e);
  if (!ks.length) return ['nullptr', 0];
  const name = `kKv${uid++}`;
  w(`static const KV ${name}[] = {${ks.map((k) => `{Ch_${k}, ${f(e[k])}}`).join(', ')}};`);
  return [name, ks.length];
};
const pupilOf = (a) => (a ? 'Pupil::' + a[0].toUpperCase() + a.slice(1) : 'Pupil::None');
const modeOf = (m) => {
  if (!m) return 'GazeMode::Keep';
  if (!GMODES.includes(m)) throw new Error('mode ' + m);
  return 'GazeMode::' + m[0].toUpperCase() + m.slice(1);
};
const keyArr = (keys) => {
  if (!keys || !keys.length) return ['nullptr', 0];
  const rows = keys.map((k) => {
    const [sn, nsn] = kvArr(k.snap);
    const [se, nse] = kvArr(k.set);
    const [ki, nki] = kvArr(k.kick);
    return `{${f(k.t)}, ${sn}, ${nsn}, ${se}, ${nse}, ${ki}, ${nki}, ${pupilOf(k.alt)}, ${k.gaze ? 'true' : 'false'}, ${f(k.gaze ? k.gaze[0] : 0)}, ${f(k.gaze ? k.gaze[1] : 0)}, ${modeOf(k.mode)}, ${f(k.shakeF || 0)}, ${k.blink | 0}}`;
  });
  const name = `kKeys${uid++}`;
  w(`static const Key ${name}[] = {`);
  rows.forEach((r) => w('    ' + r + ','));
  w('};');
  return [name, keys.length];
};

const moodNames = Object.keys(E.MOODS);
const reactNames = Object.keys(E.REACTIONS);
const moodRows = [];
for (const n of moodNames) {
  const m = E.MOODS[n];
  const full = E.__expand(Object.assign({}, E.__BASE, m.set));
  const targets = CH.map((k) => f(full[k]));
  const [ki, nki] = kvArr(m.kick);
  const [an, nan] = kvArr(m.antic && m.antic.set);
  const [ke, nke] = keyArr(m.keys);
  const ag = m.antic && m.antic.gaze;
  moodRows.push(`  {${cstr(n)}, ${cstr(m.label)}, {${targets.join(', ')}}, ${ki}, ${nki}, ${f(m.antic ? m.antic.d : 0)}, ${an}, ${nan}, ${ag ? 'true' : 'false'}, ${f(ag ? ag[0] : 0)}, ${f(ag ? ag[1] : 0)}, ${f((m.gaze || [0, 0])[0])}, ${f((m.gaze || [0, 0])[1])}, ${modeOf(m.mode || 'idle')}, ${pupilOf(m.alt)}, ${f(m.shakeF || 20)}, ${f(m.blinkSlow || 1)}, ${f(m.blinkEvery || 2)}, ${m.blink | 0}, ${ke}, ${nke}},`);
}
const reactRows = [];
for (const n of reactNames) {
  const r = E.REACTIONS[n];
  const [ke, nke] = keyArr(r.keys);
  reactRows.push(`  {${cstr(n)}, ${cstr(r.label)}, ${f(r.dur)}, ${ke}, ${nke}},`);
}
w('');
w(`static const MoodDef kMoods[${moodNames.length}] = {`);
moodRows.forEach((r) => w(r));
w('};');
w(`static const ReactionDef kReactions[${reactNames.length}] = {`);
reactRows.forEach((r) => w(r));
w('};');
w(`static constexpr int kMoodCount = ${moodNames.length};`);
w(`static constexpr int kReactionCount = ${reactNames.length};`);
w('// Expression index: moods first (0..kMoodCount-1), then reactions.');
w('enum Expr : int8_t {');
moodNames.forEach((n, i) => w(`  X_${n} = ${i},`));
reactNames.forEach((n, i) => w(`  X_${n} = ${moodNames.length + i},`));
w(`  X_Count = ${moodNames.length + reactNames.length}`);
w('};');
const pool = E.RANDOM_POOL.map((n) => 'X_' + n);
w(`static constexpr int8_t kRandomPool[] = {${pool.join(', ')}};`);
w('');

// ---- the 15 s loop ----
w('struct ScriptEv {');
w('  float t;');
w('  int8_t mood;  // -1 = none');
w('  bool look;');
w('  float lx, ly;');
w('  uint8_t blink;');
w('  float slow;');
w('  bool hop;');
w('};');
w(`static constexpr float kLoopSeconds = ${f(E.LOOP)};`);
w(`static const ScriptEv kScript[] = {`);
for (const e of E.__SCRIPT) {
  w(`    {${f(e.t)}, ${e.mood ? 'X_' + e.mood : -1}, ${e.look ? 'true' : 'false'}, ${f(e.look ? e.look[0] : 0)}, ${f(e.look ? e.look[1] : 0)}, ${e.blink | 0}, ${f(e.slow || 0)}, ${e.hop ? 'true' : 'false'}},`);
}
w('};');
w('');
w('}  // namespace eyes');
w('}  // namespace suflet');

const dst = path.join(root, 'lib', 'Suflet', 'src', 'EyeTables.h');
fs.writeFileSync(dst, out.join('\n') + '\n');
console.log(`wrote ${path.relative(root, dst)}: ${designs.length} designs, ${moodNames.length} moods, ${reactNames.length} reactions, ${CH.length} channels`);
