#!/usr/bin/env python3
"""Generate the anti-aliased glyph atlases used by Canvas::drawText.

    python3 tools/gen_font.py            # writes lib/Suflet/src/FontData.h

Glyphs are rasterised with FreeType (through Pillow) from Nunito, an OFL
font (tools/fonts/OFL.txt), and stored as 4 bits of coverage per pixel
(16 alpha levels: plenty on a 466 px AMOLED). Each size keeps
advance widths in 1/16 px so a run of text accumulates sub-pixel pen
positions and does not drift. The result is a plain C++ header of const
arrays: on the ESP32 they stay in flash (rodata), nothing is copied to RAM.

Charset: ASCII, the Romanian letters ă â î ș ț Ă Â Î Ș Ț (comma-below, the
correct forms), the keyboard's variant-tray letters (à á ä é è ...), and a
little typography („ ” “ ’ … – · ° € £ « »). The big "digits" size only
carries 0-9 and ':' for the time picker.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "lib", "Suflet", "src", "FontData.h")
FONTS = os.path.join(HERE, "fonts")

RO = "ăâîșțĂÂÎȘȚ"
TRAY = "àáäéèêëíïóôöúüçčćñšß" + "ÀÁÄÉÈÊËÍÏÓÔÖÚÜÇČĆÑŠ"
TYPO = "„”“’…–·°€£«»"
FULL = "".join(chr(c) for c in range(0x20, 0x7F)) + RO + TRAY + TYPO
DIGITS = "0123456789: "

# name, file, pixel size, charset
SIZES = [
    ("kFontSmall", "Nunito-SemiBold.ttf", 22, FULL),   # labels, suggestions, ring numerals
    ("kFontText", "Nunito-SemiBold.ttf", 26, FULL),    # keys, the text field
    ("kFontLarge", "Nunito-Bold.ttf", 36, FULL),       # key callout, variant tray
    ("kFontDigits", "Nunito-Bold.ttf", 88, DIGITS),    # time picker digits
]


def raster(font, ch):
    """Coverage bitmap of one glyph, cropped, plus its offset from the pen
    position on the baseline (x right, y down)."""
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    w, h = max(0, x1 - x0), max(0, y1 - y0)
    if w == 0 or h == 0:
        return 0, 0, 0, 0, b""
    im = Image.new("L", (w + 4, h + 4), 0)
    ImageDraw.Draw(im).text((2 - x0, 2 - y0), ch, font=font, fill=255, anchor="ls")
    bb = im.getbbox()
    if not bb:
        return 0, 0, 0, 0, b""
    im = im.crop(bb)
    ox, oy = x0 - 2 + bb[0], y0 - 2 + bb[1]
    return im.width, im.height, ox, oy, im.tobytes()


def pack4(w, h, data):
    out = bytearray()
    stride = (w + 1) // 2
    for y in range(h):
        row = data[y * w:(y + 1) * w]
        for i in range(stride):
            a = row[2 * i] if 2 * i < w else 0
            b = row[2 * i + 1] if 2 * i + 1 < w else 0
            # round to 4 bits; keep faint edges visible
            qa, qb = (a * 15 + 127) // 255, (b * 15 + 127) // 255
            out.append((qa << 4) | qb)
    return bytes(out)


def main():
    lines = [
        "// GENERATED by tools/gen_font.py - do not edit by hand.",
        "// Nunito (c) 2014 The Nunito Project Authors, SIL Open Font License 1.1",
        "// (see tools/fonts/OFL.txt). 4-bit anti-aliased coverage, rows packed",
        "// two pixels per byte (high nibble first), advances in 1/16 px.",
        "#pragma once",
        '#include "Font.h"',
        "",
        "namespace suflet {",
        "namespace fontdata {",
        "",
    ]
    total = 0
    report = []
    for name, file, px, chars in SIZES:
        font = ImageFont.truetype(os.path.join(FONTS, file), px)
        asc, desc = font.getmetrics()
        cps = sorted(set(ord(c) for c in chars))
        glyphs, bits = [], bytearray()
        for cp in cps:
            ch = chr(cp)
            w, h, ox, oy, data = raster(font, ch)
            adv16 = int(round(font.getlength(ch) * 16))
            if max(w, h) > 255 or not (-128 <= ox < 128 and -128 <= oy < 128):
                sys.exit(f"glyph {ch!r} at {px}px does not fit the table format")
            glyphs.append((cp, adv16, len(bits), w, h, ox, oy))
            bits += pack4(w, h, data)
        sym = name[len("kFont"):]
        lines.append(f"// {file} {px}px: {len(glyphs)} glyphs, {len(bits)} B bitmap")
        lines.append(f"static const uint8_t k{sym}Bits[] = {{")
        for i in range(0, len(bits), 24):
            lines.append("    " + ",".join(str(b) for b in bits[i:i + 24]) + ",")
        lines.append("};")
        lines.append(f"static const Glyph k{sym}Glyphs[] = {{")
        for g in glyphs:
            lines.append("    {0x%04X, %d, %d, %d, %d, %d, %d}," % g)
        lines.append("};")
        line_h = int(round(px * 1.23))
        lines.append(
            f"static const Font k{sym} = {{\"Nunito {px}\", {px}, {asc}, {desc}, {line_h}, "
            f"{len(glyphs)}, k{sym}Glyphs, k{sym}Bits}};")
        lines.append("")
        size = len(bits) + len(glyphs) * 12
        total += size
        report.append(f"  {name:12s} {px:3d}px {len(glyphs):4d} glyphs  {size / 1024:6.1f} KB")
    lines += ["}  // namespace fontdata", "}  // namespace suflet", ""]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("\n".join(report))
    print(f"  total flash  {total / 1024:.1f} KB -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
