#!/usr/bin/env node
// Writes test/test_suflet/motion_fixture.h: an IMU trace (a scripted session:
// tilt, spin, on its back, face down, upside down, double tap, nod, held
// still) and what the web engine's Motion (../eyes/eyes.js) makes of it, for
// the parity test of the C++ port (lib/Suflet/src/EyeMotion.cpp).
//
//   node tools/gen_motion_fixture.js      (run from firmware/)
'use strict';
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const E = require(path.resolve(root, '..', 'eyes', 'eyes.js'));

const F = (v) => { v = Math.fround(+v); if (Math.abs(v) < 1e-30) v = 0; let x = String(+v.toPrecision(8)); if (!/[.e]/.test(x)) x += '.0'; return x + 'f'; };
const D = (d) => (d * Math.PI) / 180;

const imu = new E.PoseImu();
const m = new E.Motion();
const trace = [], poses = [], cues = [];
let roll = 0, pitch = 0, yaw = 0, dt = 0.01;
let noise = null;
function feed() {
  const s = imu.sample(roll, pitch, yaw, dt);
  if (noise) { const t = trace.length * dt; s.gx += 0.05 * Math.sin(t * 57); s.gy += 0.04 * Math.sin(t * 43 + 1); s.gz += 0.03 * Math.sin(t * 71 + 2); }
  // what the device sees: floats
  const f = { dt: Math.fround(dt), a: [s.ax, s.ay, s.az].map(Math.fround), g: [s.gx, s.gy, s.gz].map(Math.fround) };
  const i = trace.length;
  trace.push(f);
  m.update(f.dt, { ax: f.a[0], ay: f.a[1], az: f.a[2], gx: f.g[0], gy: f.g[1], gz: f.g[2] });
  for (let c = m.poll(); c; c = m.poll()) cues.push([i, E.MOTION_CUES.indexOf(c)]);
  if (i % 10 === 9) { const p = m.pose; poses.push([i, p.roll, p.px, p.py, p.lid, p.dim, p.dizzy]); }
}
function to(r, p, y, s, hold) {
  const n = Math.round(s / dt), nh = Math.round((hold || 0) / dt), r0 = roll, p0 = pitch, y0 = yaw;
  for (let i = 1; i <= n + nh; i++) {
    const q = i >= n ? 1 : i / n;
    roll = r0 + (r - r0) * q; pitch = p0 + (p - p0) * q; yaw = y0 + (y - y0) * q;
    feed();
  }
}

to(0, 0, 0, 0, 0.5);
to(D(70), 0, 0, 0.4, 1.0);          // turned in the glass plane: level keeping
to(0, 0, 0, 0.4, 0.5);
to(0, 0, 12 * 2.5, 2.5, 6.5);       // a strong spin: dizzy, then ufff
to(0, D(-90), yaw, 0.5, 1.5);       // on its back: looks up at you
to(0, D(-70), yaw, 0.25, 1.0);      // tipped: marble pupils
to(0, D(90), yaw, 0.8, 1.5);        // face down
to(0, 0, yaw, 0.6, 0.5);            // face up again
dt = 1 / 60;                        // a phone's rate from here on
to(D(200), 0, yaw, 2.0, 0.5);       // round to upside down
to(0, 0, yaw, 1.0, 0.5);
for (let k = 0; k < 2; k++) { imu.lin[2] = -0.7; feed(); imu.lin[2] = 0; to(roll, pitch, yaw, 0, 0.25); }  // double tap
to(roll, pitch, yaw, 0, 0.6);
for (let i = 0; i < 90; i++) { pitch = D(20) * Math.sin(i * dt * Math.PI * 4); feed(); }  // nod
pitch = 0;
to(0, D(-25), yaw, 0.3, 0.3);
noise = true;
to(0, D(-25), yaw, 0, 3.0);         // held still in a hand

const out = [];
const w = (s) => out.push(s);
w('// GENERATED by tools/gen_motion_fixture.js from ../eyes/eyes.js v' + E.VERSION + ' (Motion). Do not edit.');
w('#pragma once');
w('');
w('struct MotionTraceIn {');
w('  float dt;');
w('  float a[3], g[3];');
w('};');
w('struct MotionPoseOut {');
w('  int i;');
w('  float roll, px, py, lid, dim, dizzy;');
w('};');
w('struct MotionCueOut {');
w('  int i, cue;');
w('};');
w('');
w('static const MotionTraceIn kMotionTrace[] = {');
for (const t of trace) w('    {' + F(t.dt) + ', {' + t.a.map(F).join(', ') + '}, {' + t.g.map(F).join(', ') + '}},');
w('};');
w('static const int kMotionTraceN = ' + trace.length + ';');
w('');
w('static const MotionPoseOut kMotionPoses[] = {');
for (const p of poses) w('    {' + p[0] + ', ' + p.slice(1).map(F).join(', ') + '},');
w('};');
w('static const int kMotionPosesN = ' + poses.length + ';');
w('');
w('// ' + cues.map((c) => E.MOTION_CUES[c[1]] + '@' + c[0]).join(' '));
w('static const MotionCueOut kMotionCues[] = {');
for (const c of cues) w('    {' + c[0] + ', ' + c[1] + '},');
w('};');
w('static const int kMotionCuesN = ' + cues.length + ';');
fs.writeFileSync(path.resolve(root, 'test', 'test_suflet', 'motion_fixture.h'), out.join('\n') + '\n');
console.log('motion_fixture.h:', trace.length, 'samples,', poses.length, 'poses,', cues.length, 'cues:', cues.map((c) => E.MOTION_CUES[c[1]]).join(' '));
