#!/usr/bin/env node
// Writes test/test_suflet/eye_fixture.h: ground truth produced by the web
// engine (../eyes/eyes.js) for the native parity tests of the C++ port.
//   - the birth roll for 600 chip ids (edge cases + a deterministic spread)
//   - rig traces: scripted expressions, looks and blinks, sampled every 1/8 s
//
//   node tools/gen_eye_fixture.js      (run from firmware/)
'use strict';
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const E = require(path.resolve(root, '..', 'eyes', 'eyes.js'));
const designs = require(path.resolve(root, '..', 'eyes', 'designs.json')).designs;

const out = [];
const F = (v) => { let x = String(+(+v).toPrecision(7)); if (!/[.e]/.test(x)) x += '.0'; return x + 'f'; };
const w = (s) => out.push(s);
w('// GENERATED by tools/gen_eye_fixture.js from ../eyes/eyes.js v' + E.VERSION + '. Do not edit.');
w('#pragma once');
w('#include <stdint.h>');
w('');
w('struct RollCase {');
w('  uint8_t mac[6];');
w('  int16_t design;  // index into designs.json');
w('  uint8_t rarity;');
w('};');

// chip ids: edges + a deterministic xorshift spread
const ids = ['000000000000', 'FFFFFFFFFFFF', '000000000001', '800000000000', 'C0FFEEC0FFEE', 'A1B2C3D4E5F6', '24587C9A1B2C'];
let s = 0x1234567;
const xs = () => { s ^= s << 13; s >>>= 0; s ^= s >>> 17; s ^= s << 5; s >>>= 0; return s; };
while (ids.length < 600) ids.push((xs().toString(16).padStart(8, '0') + xs().toString(16).padStart(8, '0')).slice(0, 12).toUpperCase());
w(`static const RollCase kRollCases[${ids.length}] = {`);
for (const id of ids) {
  const r = E.rollFromChipId(designs, id);
  const di = designs.indexOf(r.design);
  const ri = E.RARITIES.findIndex((x) => x.key === r.rarity);
  const mac = id.match(/.{2}/g).map((h) => '0x' + h).join(', ');
  w(`    {{${mac}}, ${di}, ${ri}},`);
}
w('};');
w('');

// rig traces
const FIELDS = ['scale', 'sy', 'lidL', 'lidR', 'smileL', 'pupilL', 'altL', 'shift', 'bob', 'rot', 'zzz'];
const scripts = [
  { name: 'idle', seed: E.hashStr('original') ^ 0x5eed, secs: 12, ev: [] },
  { name: 'moods', seed: 12345, secs: 14, ev: [[0.5, 'set', 'happy'], [2.0, 'set', 'surprised'], [3.5, 'set', 'smirk'], [5.0, 'set', 'love'], [6.5, 'set', 'sleepy'], [8.0, 'set', 'angry'], [9.5, 'set', 'dizzy'], [11.0, 'set', 'neutral']] },
  { name: 'reactions', seed: 777, secs: 14, ev: [[0.3, 'set', 'laugh'], [2.5, 'set', 'sneeze'], [4.6, 'react', 'shy', 1.6], [6.6, 'set', 'startled'], [9.0, 'set', 'hello'], [10.8, 'set', 'wink'], [12.0, 'react', 'confused', 1.4]] },
  { name: 'look', seed: 42, secs: 6, ev: [[0.5, 'look', 0.8, -0.3], [1.5, 'blink', 2], [2.0, 'look', -0.6, 0.5], [3.0, 'hop'], [3.5, 'nolook'], [4.0, 'set', 'working'], [5.0, 'set', 'listening']] },
];
w('struct RigEvent {');
w('  float t;');
w('  uint8_t kind;  // 0 set, 1 react, 2 look, 3 nolook, 4 blink, 5 hop');
w('  const char* name;');
w('  float a, b;');
w('};');
w('struct RigTrace {');
w('  const char* name;');
w('  uint32_t seed;');
w('  float secs;');
w('  const RigEvent* ev;');
w('  int nEv;');
w('  const float* samples;  // every 1/8 s: ' + FIELDS.join(', ') + ', pL0, pL1, pR0, eyeG0, closed, level');
w('  int nSamples;');
w('};');
const KIND = { set: 0, react: 1, look: 2, nolook: 3, blink: 4, hop: 5 };
const traceRows = [];
scripts.forEach((sc, si) => {
  const rig = new E.Rig(sc.seed >>> 0, 'live');
  const steps = Math.round(sc.secs * 32);
  const samples = [];
  let ei = 0;
  for (let i = 0; i < steps; i++) {
    const t = i / 32;
    while (ei < sc.ev.length && sc.ev[ei][0] <= t + 1e-9) {
      const e = sc.ev[ei++];
      if (e[1] === 'set') rig.setExpression(e[2]);
      else if (e[1] === 'react') rig.react(e[2], e[3]);
      else if (e[1] === 'look') rig.look = [e[2], e[3]];
      else if (e[1] === 'nolook') rig.look = null;
      else if (e[1] === 'blink') rig.blink(e[2]);
      else if (e[1] === 'hop') rig.hop();
    }
    rig.update(1 / 32);
    if (i % 4 === 3) {
      const v = FIELDS.map((k) => rig.s[k].x).concat([rig.pL[0].x, rig.pL[1].x, rig.pR[0].x, rig.eyeG[0].x, rig.closed(), rig.level]);
      samples.push(v.map(F).join(', '));
    }
  }
  w(`static const RigEvent kEv${si}[] = {`);
  if (!sc.ev.length) w('    {0.0f, 255, nullptr, 0.0f, 0.0f},');
  for (const e of sc.ev) {
    const name = typeof e[2] === 'string' ? JSON.stringify(e[2]) : 'nullptr';
    const a = typeof e[2] === 'number' ? e[2] : (e[3] || 0);
    const b = typeof e[2] === 'number' ? (e[3] || 0) : 0;
    w(`    {${F(e[0])}, ${KIND[e[1]]}, ${name}, ${F(a)}, ${F(b)}},`);
  }
  w('};');
  w(`static const float kSamples${si}[] = {`);
  samples.forEach((r) => w('    ' + r + ','));
  w('};');
  traceRows.push(`    {${JSON.stringify(sc.name)}, ${sc.seed >>> 0}u, ${F(sc.secs)}, kEv${si}, ${sc.ev.length}, kSamples${si}, ${samples.length}},`);
});
w(`static constexpr int kTraceFields = ${FIELDS.length + 6};`);
w(`static const RigTrace kTraces[${scripts.length}] = {`);
traceRows.forEach((r) => w(r));
w('};');

const dst = path.join(root, 'test', 'test_suflet', 'eye_fixture.h');
fs.writeFileSync(dst, out.join('\n') + '\n');
console.log('wrote', path.relative(root, dst));
