#!/usr/bin/env python3
"""Generate the keyboard's EN + RO lexicon header from tools/words/*.txt.

    python3 tools/gen_words.py         # writes lib/Suflet/src/WordListData.h

Each word is stored with its "folded" key (lower case, no diacritics, no
hyphen/apostrophe), so `sa` finds `să`, `intro` finds `într-o` and `dont`
finds `don't`. See tools/words/README.md for the licence of the lists.
"""
import os
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "words")
OUT = os.path.join(ROOT, "lib", "Suflet", "src", "WordListData.h")

RO_DIAC = set("ăâîșțĂÂÎȘȚ")


def norm(s):
    return s.replace("ş", "ș").replace("ţ", "ț").replace("Ş", "Ș").replace("Ţ", "Ț")


def fold(s):
    s = unicodedata.normalize("NFD", norm(s).lower())
    s = "".join(c for c in s if not unicodedata.combining(c))
    return s.replace("-", "").replace("'", "").replace("’", "")


def read_list(name):
    out = []
    for line in open(os.path.join(SRC, name), encoding="utf-8"):
        line = line.strip()
        if line and not line.startswith("#"):
            out.append(norm(line))
    return out


def c(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ro, en = read_list("ro.txt"), read_list("en.txt")
    # A typed Romanian word is "exact evidence" of Romanian (used when the UI is
    # English) if it is written the way it appears in the list and no
    # diacritic sibling shares its folded key ("la", "mâine", "amintește-mi"
    # count; "sa" or "tara" do not).
    entries = []
    for lang, words in (("ro", ro), ("en", en)):
        seen = set()
        for rank, w in enumerate(words):
            if w in seen:
                continue
            seen.add(w)
            f = fold(w)
            exact = False
            if lang == "ro":
                has_d = any(ch in RO_DIAC for ch in w)
                plain = f == w.replace("-", "").replace("'", "")
                sibling = any(x != w and fold(x) == f and any(ch in RO_DIAC for ch in x) for x in ro)
                exact = (has_d or plain) and not sibling
            entries.append((w, f, rank, 1 if lang == "ro" else 0, 1 if exact else 0))
    auto = []
    for line in read_list("auto.txt"):
        k, v = line.split(":", 1)
        auto.append((k, v))
    nxt = []
    for line in read_list("next.txt"):
        head, words = line.split(":", 1)
        lang, prev = head.split()
        ws = words.split()
        assert len(ws) == 3, line
        nxt.append((1 if lang == "ro" else 0, "" if prev == "-" else prev, ws))

    L = [
        "// GENERATED by tools/gen_words.py from tools/words/*.txt - do not edit.",
        "// Hand-written project word lists (no third-party corpus), see",
        "// tools/words/README.md.",
        "#pragma once",
        '#include "Predictor.h"',
        "",
        "namespace suflet {",
        "namespace words {",
        "",
        "static const WordEntry kLexicon[] = {",
    ]
    for w, f, r, lang, ex in entries:
        L.append(f"    {{{c(w)}, {c(f)}, {r}, {lang}, {ex}}},")
    L += ["};", "", "static const AutoEntry kAuto[] = {"]
    for k, v in auto:
        L.append(f"    {{{c(k)}, {c(v)}}},")
    L += ["};", "", "static const NextEntry kNext[] = {"]
    for lang, prev, ws in nxt:
        L.append(f"    {{{lang}, {c(prev)}, {{{', '.join(c(x) for x in ws)}}}}},")
    L += ["};", "", "}  // namespace words", "}  // namespace suflet", ""]
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print(f"{len(entries)} words ({len(ro)} RO, {len(en)} EN), {len(auto)} auto forms, "
          f"{len(nxt)} next-word rows -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
