// GENERATED by ai/tools/record_frames.py from the running SOUL Cloud (suflet_ai.app). Do not edit:
// run `python tools/record_frames.py` in ai/ to record again. Frames in arrival order; socket_start marks
// a new WebSocket. The device token in the auth answer is replaced by a placeholder of the same length.
#pragma once
#include <stdint.h>

struct RecordedFrame {
  const char* t;
  bool socket_start;
  const char* json;
};

static const RecordedFrame kRecordedFrames[] = {
    {"welcome", true, "{\"v\":1,\"t\":\"welcome\",\"server_time\":1791024828,\"tz\":\"Europe/Bucharest\",\"posix_tz\":\"EET-2EEST,M3.5.0/3,M10.5.0/4\",\"state\":\"pending\",\"owner\":\"\",\"brain\":\"none\",\"voice\":\"claude\",\"lang\":\"en\",\"quiet\":{\"from\":\"22:00\",\"to\":\"07:00\"},\"connectors_paused\":false,\"limits\":{\"ask_per_min\":20,\"ask_per_day\":600,\"frames_per_s\":2},\"allowance\":null,\"trial\":null,\"models\":{\"claude\":\"claude-haiku-4-5\",\"openai\":\"gpt-6-luna\"}}"},
    {"replay.done", false, "{\"v\":1,\"t\":\"replay.done\",\"last\":0}"},
    {"pairing", false, "{\"v\":1,\"t\":\"pairing\",\"code\":\"P8GECKCH\",\"expires_in\":600,\"url\":\"https://127.0.0.1:52549/pair#c=P8GECKCH&d=soul-c0ffee123456\"}"},
    {"pair.confirm", false, "{\"v\":1,\"t\":\"pair.confirm\",\"pid\":\"p_qRpaXXphtm5fAH0l\",\"name\":\"Ana\",\"account_hint\":\"a***@example.com\",\"expires_in\":120}"},
    {"paired", false, "{\"v\":1,\"t\":\"paired\",\"owner\":\"Ana\",\"account_hint\":\"a***@example.com\"}"},
    {"inbox.state", false, "{\"v\":1,\"t\":\"inbox.state\",\"pending\":0,\"answered\":0}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":1,\"action\":\"note.create\",\"args\":{\"text\":\"Buy batteries \342\200\224 \310\231i lapte\",\"tags\":[\"shop\"]},\"item_id\":\"it_n1\",\"origin\":{\"kind\":\"connector\",\"app\":\"claude\",\"by\":\"Ana\"},\"say\":\"From Claude: noted.\"}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":2,\"action\":\"reminder.create\",\"args\":{\"when\":\"2030-10-03T03:00\",\"text\":\"Call the bank\"},\"item_id\":\"it_r1\",\"origin\":{\"kind\":\"connector\",\"app\":\"claude\",\"by\":\"Ana\"},\"needs_accept\":true}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":3,\"action\":\"reminder.create\",\"args\":{\"when\":\"2020-10-01T08:00\",\"text\":\"Pills\"},\"item_id\":\"it_r0\",\"origin\":{\"kind\":\"connector\",\"app\":\"claude\",\"by\":\"Ana\"},\"missed\":true}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":4,\"action\":\"alarm.set\",\"args\":{\"hhmm\":\"07:30\",\"days\":[\"mon\",\"tue\",\"wed\",\"thu\",\"fri\"],\"label\":\"Work\"},\"item_id\":\"it_a1\",\"origin\":{\"kind\":\"connector\",\"app\":\"claude\",\"by\":\"Ana\"}}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":5,\"action\":\"timer.start\",\"args\":{\"seconds\":90,\"label\":\"tea\"},\"item_id\":\"it_t1\",\"origin\":{\"kind\":\"app\"}}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":6,\"action\":\"focus.start\",\"args\":{\"minutes\":25,\"label\":\"write\"},\"item_id\":\"it_f1\",\"origin\":{\"kind\":\"app\"}}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":7,\"action\":\"answer.show\",\"args\":{\"title\":\"Pancakes\",\"body\":\"1. flour\\n2. eggs\"},\"item_id\":\"it_c1\",\"origin\":{\"kind\":\"connector\",\"app\":\"claude\",\"by\":\"Ana\"},\"say\":\"Here are the steps\",\"private\":true,\"expires_at\":1791046428}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":8,\"action\":\"item.delete\",\"args\":{\"item_id\":\"it_a1\"},\"item_id\":\"it_a1\",\"origin\":{\"kind\":\"app\"}}"},
    {"config", false, "{\"v\":1,\"t\":\"config\",\"brain\":\"none\"}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":9,\"action\":\"reminder.create\",\"args\":{\"when\":\"2026-10-04T09:00\",\"text\":\"call mom\"},\"item_id\":\"it_1\",\"origin\":{\"kind\":\"turn\"}}"},
    {"reply", false, "{\"v\":1,\"t\":\"reply\",\"re\":\"a1\",\"conv\":\"c_MaS0b3mJ9vco9e2E\",\"say\":\"Done, I'll remind you tomorrow at 09:00: call mom.\",\"face\":\"happy\",\"chips\":[],\"provider\":\"rules\",\"brain\":\"none\",\"seqs\":[9]}"},
    {"added", false, "{\"v\":1,\"t\":\"added\",\"cid\":\"c0ffee0000000001\",\"item_id\":\"it_2\"}"},
    {"added", false, "{\"v\":1,\"t\":\"added\",\"cid\":\"c0ffee0000000002\",\"item_id\":\"ib_AysO1_2d-mG1\"}"},
    {"inbox.state", false, "{\"v\":1,\"t\":\"inbox.state\",\"pending\":1,\"answered\":0}"},
    {"error", false, "{\"v\":1,\"t\":\"error\",\"code\":\"too_big\",\"msg\":\"frame over 10 KB\",\"re\":\"big1\",\"cid\":\"c0ffee0000000003\"}"},
    {"error", false, "{\"v\":1,\"t\":\"error\",\"code\":\"invalid\",\"msg\":\"invalid arguments: hhmm: Value error, hhmm must be 24h HH:MM\",\"cid\":\"c0ffee0000000004\"}"},
    {"config", false, "{\"v\":1,\"t\":\"config\",\"tz\":\"Europe/London\",\"posix_tz\":\"GMT0BST,M3.5.0/1,M10.5.0\",\"quiet\":{\"from\":\"23:00\",\"to\":\"07:00\"}}"},
    {"welcome", true, "{\"v\":1,\"t\":\"welcome\",\"server_time\":1791024829,\"tz\":\"Europe/London\",\"posix_tz\":\"GMT0BST,M3.5.0/1,M10.5.0\",\"state\":\"paired\",\"owner\":\"Ana\",\"brain\":\"none\",\"voice\":\"claude\",\"lang\":\"en\",\"quiet\":{\"from\":\"23:00\",\"to\":\"07:00\"},\"connectors_paused\":false,\"limits\":{\"ask_per_min\":20,\"ask_per_day\":600,\"frames_per_s\":2},\"allowance\":null,\"trial\":null,\"models\":{\"claude\":\"claude-haiku-4-5\",\"openai\":\"gpt-6-luna\"}}"},
    {"push", false, "{\"v\":1,\"t\":\"push\",\"seq\":10,\"action\":\"note.create\",\"args\":{\"text\":\"While you were away\",\"tags\":[]},\"item_id\":\"it_n2\",\"origin\":{\"kind\":\"connector\",\"app\":\"claude\",\"by\":\"Ana\"}}"},
    {"replay.done", false, "{\"v\":1,\"t\":\"replay.done\",\"last\":10}"},
    {"inbox.state", false, "{\"v\":1,\"t\":\"inbox.state\",\"pending\":1,\"answered\":0}"},
    {"welcome", true, "{\"v\":1,\"t\":\"welcome\",\"server_time\":1791024829,\"tz\":\"Europe/London\",\"posix_tz\":\"GMT0BST,M3.5.0/1,M10.5.0\",\"state\":\"paired\",\"owner\":\"Ana\",\"brain\":\"none\",\"voice\":\"claude\",\"lang\":\"en\",\"quiet\":{\"from\":\"23:00\",\"to\":\"07:00\"},\"connectors_paused\":false,\"limits\":{\"ask_per_min\":20,\"ask_per_day\":600,\"frames_per_s\":2},\"allowance\":null,\"trial\":null,\"models\":{\"claude\":\"claude-haiku-4-5\",\"openai\":\"gpt-6-luna\"}}"},
    {"resync", false, "{\"v\":1,\"t\":\"resync\",\"last\":10}"},
    {"replay.done", false, "{\"v\":1,\"t\":\"replay.done\",\"last\":10}"},
    {"inbox.state", false, "{\"v\":1,\"t\":\"inbox.state\",\"pending\":1,\"answered\":0}"},
    {"unpaired", false, "{\"v\":1,\"t\":\"unpaired\",\"reason\":\"user\"}"},
};

static const char* const kRecordedTypes[] = {"welcome", "replay.done", "pairing", "pair.confirm", "paired", "inbox.state", "push", "config", "reply", "added", "error", "resync", "unpaired"};
static const int kRecordedMin = 32;
static const int kRecordedMinPushes = 6;
static const char* const kRecordedFinalState = "unpaired";
static const uint32_t kRecordedLastSeq = 10u;

struct RecordedHttp {
  const char* what;
  int status;
  const char* body;
};

static const RecordedHttp kRecordedHttp[] = {
    {"challenge", 200, "{\"nonce\":\"xRxFmV56jNLQHPauBo9ANj895nMoz2sEOQ4cSYInecI\",\"expires_in\":60}"},
    {"auth_ok", 200, "{\"token\":\"sdt_RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR\",\"expires_in\":86400,\"ws_url\":\"wss://127.0.0.1:52549/v1/device/ws\",\"server_time\":1791024828,\"state\":\"pending\",\"owner\":\"\",\"trial\":null}"},
    {"auth_bad_nonce", 400, "{\"error\":{\"code\":\"bad_nonce\",\"msg\":\"nonce unknown, used, expired or from another network\"}}"},
    {"auth_bad_signature", 401, "{\"error\":{\"code\":\"bad_signature\",\"msg\":\"signature does not verify\"}}"},
};
