#!/usr/bin/env python3
"""Fixtures for the SoulOS apps, made by the real cloud code (maps.py, apps.py), so the firmware simulator, the
native tests and the web prototype all draw exactly what SOUL Cloud would send:

    firmware/sim/app_fixtures.h        C arrays: SMB1 bundles (z 15, 16, 17), a route, weather, agenda, rates
    os/index.html                      the same data between /* SOUL-APPDATA */ markers (base64 bundle + JSON)

The map is the synthetic demo city of maps.demo_city_tiles (not OpenStreetMap data).

    python3 ai/tools/gen_app_fixtures.py
"""
from __future__ import annotations

import base64
import datetime as dt
import json
import re
import sys
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "ai"))
from suflet_ai import maps as M  # noqa: E402
from suflet_ai.apps import parse_ics, weather_for_device  # noqa: E402

LAT, LON = 44.4355, 26.1025


def route() -> dict:
    """A walk through the demo city's grid: north on Calea Victoriei, right, left, there."""
    z = 15
    cx, cy = M.world_px(LAT, LON, z)
    wp = [(cx - 2, cy + 40), (cx - 8, cy - 110), (cx - 12, cy - 146), (cx + 80, cy - 142), (cx + 168, cy - 138),
          (cx + 172, cy - 200), (cx + 176, cy - 262)]
    pts = []
    for (x0, y0), (x1, y1) in zip(wp, wp[1:]):
        for i in range(6):
            t = i / 6
            pts.append(M.lat_lon(x0 + (x1 - x0) * t, y0 + (y1 - y0) * t, z))
    pts.append(M.lat_lon(*wp[-1], z))
    steps = [M.Step("depart", 0, 0, "Calea Victoriei"), M.Step("right", 0, 12, "Strada Academiei"),
             M.Step("left", 0, 24, "Strada Ion Câmpineanu"), M.Step("arrive", 0, len(pts) - 1)]
    cum = [0.0]
    for a, b in zip(pts, pts[1:]):
        cum.append(cum[-1] + M.haversine(*a, *b))
    for i, s in enumerate(steps[:-1]):
        s.dist_m = cum[steps[i + 1].idx] - cum[s.idx]
    r = M.Route(pts, cum[-1], cum[-1] / 1.35, steps, "walk", "Ateneul Român", pts[-1][0], pts[-1][1], "demo", "rt00001")
    return r.device_json()


OM = {"current": {"temperature_2m": 21.4, "weather_code": 2, "apparent_temperature": 20.2, "wind_speed_10m": 11.6},
      "hourly": {"time": [f"2026-09-26T{h:02d}:00" for h in range(18, 24)] + [f"2026-09-27T{h:02d}:00" for h in range(0, 7)],
                 "temperature_2m": [21, 20, 19, 18, 17, 16.4, 15.8, 15.2, 14.6, 14, 13.6, 13.2, 13],
                 "weather_code": [2, 2, 1, 0, 0, 0, 0, 0, 1, 2, 3, 61, 61], "precipitation_probability": [5] * 11 + [40, 55]},
      "daily": {"time": ["2026-09-26", "2026-09-27", "2026-09-28", "2026-09-29"], "weather_code": [2, 61, 0, 3],
                "temperature_2m_max": [24.2, 18, 20, 19], "temperature_2m_min": [13, 11, 9, 10],
                "precipitation_probability_max": [10, 80, 0, 20]}}

ICS = "\r\n".join([
    "BEGIN:VCALENDAR", "VERSION:2.0",
    "BEGIN:VEVENT", "SUMMARY:Coffee with Ana", "LOCATION:Origo, Lipscani 9", "DTSTART;TZID=Europe/Bucharest:20260926T193000",
    "DTEND;TZID=Europe/Bucharest:20260926T203000", "END:VEVENT",
    "BEGIN:VEVENT", "SUMMARY:Yoga", "DTSTART;TZID=Europe/Bucharest:20260927T090000", "DURATION:PT1H", "RRULE:FREQ=WEEKLY;BYDAY=SU,WE", "END:VEVENT",
    "BEGIN:VEVENT", "SUMMARY:Mum's birthday", "DTSTART;VALUE=DATE:20260928", "DTEND;VALUE=DATE:20260929", "END:VEVENT",
    "BEGIN:VEVENT", "SUMMARY:Dentist", "LOCATION:Str. Academiei 2", "DTSTART;TZID=Europe/Bucharest:20260929T150000",
    "DTEND;TZID=Europe/Bucharest:20260929T153000", "END:VEVENT",
    "END:VCALENDAR", ""])

RATES = {"base": "EUR", "date": "2026-09-25", "rates": {"USD": 1.0912, "GBP": 0.8391, "RON": 4.9746, "CHF": 0.9402,
                                                        "HUF": 396.2, "PLN": 4.281, "JPY": 161.7, "TRY": 37.42}}


def c_bytes(name: str, b: bytes) -> str:
    rows = [", ".join(f"0x{x:02x}" for x in b[i:i + 20]) for i in range(0, len(b), 20)]
    return f"static const unsigned char {name}[{len(b)}] = {{\n  " + ",\n  ".join(rows) + "\n};\n"


def c_str(name: str, s: str) -> str:
    esc = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'static const char {name}[] = "{esc}";\n'


def main() -> int:
    tiles = M.demo_city_tiles(LAT, LON, 15, radius=2)
    src = M.DemoTiles(tiles, 15)
    bundles = {z: M.build_bundle(src, LAT, LON, z) for z in (15, 16, 17)}
    rt = route()
    weather = weather_for_device(OM, "en", "București")
    now = dt.datetime(2026, 9, 26, 18, 38, tzinfo=ZoneInfo("Europe/Bucharest"))
    agenda = {"events": parse_ics(ICS, "Europe/Bucharest", now), "tz": "Europe/Bucharest"}
    out = ["// Generated by ai/tools/gen_app_fixtures.py from the real cloud code (maps.py, apps.py). Do not edit.",
           "// The map is the synthetic demo city of maps.demo_city_tiles (not OpenStreetMap data).",
           "#pragma once", f"static const double kFixLat = {LAT}, kFixLon = {LON};"]
    for z, b in bundles.items():
        out.append(c_bytes(f"kFixBundle{z}", b))
    out.append(c_str("kFixRoute", json.dumps(rt, ensure_ascii=False)))
    out.append(c_str("kFixWeather", json.dumps(weather, ensure_ascii=False)))
    out.append(c_str("kFixAgenda", json.dumps(agenda, ensure_ascii=False)))
    out.append(c_str("kFixRates", json.dumps(RATES)))
    (ROOT / "firmware/sim/app_fixtures.h").write_text("\n".join(out))
    data = {"lat": LAT, "lon": LON, "bundles": {str(z): base64.b64encode(b).decode() for z, b in bundles.items()},
            "route": rt, "weather": weather, "agenda": agenda, "rates": RATES}
    blob = "/* SOUL-APPDATA */const APPDATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";/* /SOUL-APPDATA */"
    html = ROOT / "os/index.html"
    s = html.read_text()
    if "/* SOUL-APPDATA */" in s:
        s = re.sub(r"/\* SOUL-APPDATA \*/.*?/\* /SOUL-APPDATA \*/", lambda _m: blob, s, flags=re.S)
        html.write_text(s)
        print("os/index.html: APPDATA updated")
    print({z: len(b) for z, b in bundles.items()}, "route", len(json.dumps(rt)), "B")
    return 0


if __name__ == "__main__":
    sys.exit(main())
