// `soul-bridge setup`: prepares a dedicated, empty folder where the user starts
// his own Claude Code with the SOUL channel. Nothing here touches Claude's
// login: the user signs in to Claude Code himself (`claude`, then /login).
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export function workDir() {
  return process.env.SOUL_CLAUDE_DIR || path.join(os.homedir(), 'SOUL-Claude')
}

/** The command line the launcher runs (documented in docs/08-OWN-CLAUDE.md §3.1). */
export function launchArgs() {
  return [
    '--dangerously-load-development-channels', 'server:soul',
    // no built-in tools at all: a SOUL question can't run shell or touch files
    '--tools', '',
    // the reply tool needs no permission prompt
    '--allowedTools', 'mcp__soul__soul_reply', 'mcp__soul__soul_status',
    '--name', 'SOUL',
  ]
}

const shq = (s) => `'${String(s).replace(/'/g, `'\\''`)}'` // a POSIX single-quoted word

/**
 * macOS (`Start SOUL.command`, double-clicked: Terminal runs it with /bin/sh, and a non-login PATH) and Linux.
 * Finds `claude` in the usual install places, opens the status page, runs Claude Code in the foreground and keeps
 * the window open afterwards so the user can read why it stopped.
 */
export function shLauncher({ dir, nodePath, binPath, args }) {
  return `#!/bin/sh
# Starts YOUR Claude Code (signed in by you) with the SOUL channel. Keep this window open.
# Generated by \`soul-bridge setup\`: no password, token or key in here.
cd ${shq(dir)} || exit 1
PATH="$HOME/.local/bin:$HOME/.claude/local:$HOME/.npm-global/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
export PATH
export MCP_PROTOCOL_NEGOTIATION=legacy
if ! command -v claude >/dev/null 2>&1; then
  echo "Claude Code is not installed (or not on PATH). Install it from https://code.claude.com, run claude once"
  echo "and sign in to your own Claude account, then double-click Start SOUL again."
  printf 'Press Enter to close. '
  read -r _
  exit 1
fi
${shq(nodePath)} ${shq(binPath)} status-page --open >/dev/null 2>&1 &
page=$!
trap 'kill "$page" 2>/dev/null' EXIT INT TERM
claude ${args}
code=$?
echo
echo "Claude Code stopped (exit $code). SOUL now says your computer is offline."
printf 'Press Enter to close. '
read -r _
exit "$code"
`
}

/** Windows (`Start SOUL.cmd`, double-clicked). UTF-8 console for non-ASCII folders; `call` so the window stays. */
export function cmdLauncher({ dir, nodePath, binPath, args }) {
  const q = (s) => `"${String(s).replace(/%/g, '%%')}"`
  return [
    '@echo off',
    'rem Starts YOUR Claude Code (signed in by you) with the SOUL channel. Keep this window open.',
    'rem Generated by `soul-bridge setup`: no password, token or key in here.',
    'chcp 65001 >nul',
    `cd /d ${q(dir)} || exit /b 1`,
    'set MCP_PROTOCOL_NEGOTIATION=legacy',
    'where claude >nul 2>nul',
    'if errorlevel 1 (',
    '  echo Claude Code is not installed ^(or not on PATH^). Install it from https://code.claude.com, run claude once',
    '  echo and sign in to your own Claude account, then double-click Start SOUL again.',
    '  pause',
    '  exit /b 1',
    ')',
    `start "" /b ${q(nodePath)} ${q(binPath)} status-page --open`,
    `call claude ${args}`,
    'echo.',
    'echo Claude Code stopped. SOUL now says your computer is offline.',
    'pause',
    '',
  ].join('\r\n')
}

export function setup({ dir = workDir(), nodePath = process.execPath, binPath, desktop = false } = {}) {
  // fileURLToPath, not URL.pathname: on Windows that is /C:/... with %20 for spaces
  binPath = binPath || fileURLToPath(new URL('../bin/soul-bridge.js', import.meta.url))
  fs.mkdirSync(path.join(dir, '.claude'), { recursive: true })
  const mcp = { mcpServers: { soul: { command: nodePath, args: [binPath, 'channel'] } } }
  fs.writeFileSync(path.join(dir, '.mcp.json'), JSON.stringify(mcp, null, 2) + '\n')
  const settings = {
    // pre-approve only this project's SOUL server (avoids the "new MCP server" dialog)
    enabledMcpjsonServers: ['soul'],
    permissions: {
      allow: ['mcp__soul__soul_reply', 'mcp__soul__soul_status'],
      deny: ['Bash', 'Edit', 'Write', 'NotebookEdit', 'Read', 'WebFetch'],
    },
  }
  fs.writeFileSync(path.join(dir, '.claude', 'settings.json'), JSON.stringify(settings, null, 2) + '\n')
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'),
    '# SOUL\n\nThis folder only exists so the SOUL channel can reach you. Questions from SOUL arrive as ' +
    '<channel source="soul"> events: answer each one with the soul_reply tool, briefly, in the question\'s language.\n')

  const args = launchArgs().map((a) => (a === '' ? '""' : a)).join(' ')
  const files = {
    sh: path.join(dir, 'start-soul.sh'),
    command: path.join(dir, 'Start SOUL.command'), // double-click on macOS
    cmd: path.join(dir, 'Start SOUL.cmd'), // double-click on Windows
  }
  fs.writeFileSync(files.sh, shLauncher({ dir, nodePath, binPath, args }), { mode: 0o755 })
  fs.writeFileSync(files.command, shLauncher({ dir, nodePath, binPath, args }), { mode: 0o755 })
  fs.writeFileSync(files.cmd, cmdLauncher({ dir, nodePath, binPath, args }))
  try { fs.chmodSync(files.sh, 0o755); fs.chmodSync(files.command, 0o755) } catch {}
  if (desktop) { // optional: a Start SOUL icon on the Desktop (macOS / Windows)
    const d = path.join(os.homedir(), 'Desktop')
    if (fs.existsSync(d)) {
      const src = process.platform === 'win32' ? files.cmd : files.command
      const dst = path.join(d, path.basename(src))
      fs.copyFileSync(src, dst)
      try { fs.chmodSync(dst, 0o755) } catch {}
      files.desktop = dst
    }
  }
  return { dir, files, mcp, settings }
}
