#!/usr/bin/env python3
"""
build_all.py -- Micul Smecher / SUFLET enclosure: export every STL, check it, render previews.

  python3 build_all.py            STLs + checks + PNG renders + renders/lineup.png
  python3 build_all.py --stl      only STLs + checks
  python3 build_all.py --png      only PNG renders + lineup (needs the STLs for nothing, renders from the .scad)
  python3 build_all.py -j 2       parallel OpenSCAD jobs (default: number of CPUs)

Needs: openscad (tested 2021.01), xvfb-run for headless PNG, python3 + Pillow.
Outputs: stl/ms<board>_<shape>_<part>.stl, stl/CHECKS.txt, stl/dims.json, renders/*.png, renders/lineup.png
"""
import concurrent.futures as cf, json, os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCAD = os.path.join(HERE, 'micul_smecher.scad')
STL = os.path.join(HERE, 'stl')
PNG = os.path.join(HERE, 'renders')
BOARDS = ['1.43', '1.75']
SHAPES = ['coin', 'drop', 'gem', 'cloud']
PARTS = ['front', 'back', 'cap', 'lens']
EXTRA = [('1.43', 'coin', 'stand')]          # the desk stand is made for the Founders Desk Edition (1.43 coin)


def tag(b, s, p): return 'ms%s_%s_%s' % (b.replace('.', ''), s, p)


def scad(out, b, s, p, extra=(), png=None):
    cmd = ['openscad', '-o', out, '-D', 'board="%s"' % b, '-D', 'shape="%s"' % s, '-D', 'part="%s"' % p]
    for d in extra: cmd += ['-D', d]
    if png:
        cmd = ['xvfb-run', '-a', '-s', '-screen 0 1600x1200x24'] + cmd + png
    cmd.append(SCAD)
    r = subprocess.run(cmd, capture_output=True, text=True)
    log = r.stdout + r.stderr
    if r.returncode != 0 or 'ERROR' in log:
        raise RuntimeError('openscad failed for %s:\n%s' % (out, log[-2000:]))
    return log


def dims_from(log):
    m = re.search(r'MS_DIMS ([^"]+)"', log)
    d = dict(kv.split('=', 1) for kv in m.group(1).split(' ') if '=' in kv) if m else {}
    m = re.search(r'MS_STAND ([^"]+)"', log)
    if m: d['stand'] = m.group(1)
    return d


def build_stl(jobs):
    os.makedirs(STL, exist_ok=True)
    todo = [(b, s, p) for b in BOARDS for s in SHAPES for p in PARTS] + EXTRA
    dims = {}
    with cf.ThreadPoolExecutor(jobs) as ex:
        futs = {ex.submit(scad, os.path.join(STL, tag(*t) + '.stl'), *t): t for t in todo}
        for f in cf.as_completed(futs):
            b, s, p = futs[f]
            log = f.result()
            print('  stl', tag(b, s, p), flush=True)
            if p == 'front' or p == 'stand':
                dims.setdefault('%s_%s' % (b, s), {}).update(dims_from(log))
    json.dump(dims, open(os.path.join(STL, 'dims.json'), 'w'), indent=1, sort_keys=True)
    sys.path.insert(0, HERE)
    import check_stl
    files = sorted(os.path.join(STL, f) for f in os.listdir(STL) if f.endswith('.stl'))
    res = [check_stl.check(f) for f in files]
    lines = ['%-30s %8s %6s %6s %6s %5s %10s  %-20s %s' % ('file', 'tris', 'nonman', 'orient', 'degen', 'shell', 'vol_mm3', 'bbox_mm (print pose)', 'result')]
    for r in res:
        lines.append('%-30s %8d %6d %6d %6d %5d %10.1f  %-20s %s' % (
            os.path.basename(r['file']), r['triangles'], r['non_manifold_edges'], r['misoriented_edges'],
            r['degenerate'], r['shells'], r['volume_mm3'], 'x'.join('%.1f' % v for v in r['bbox_mm']),
            'OK' if r['ok'] else 'FAIL'))
    open(os.path.join(STL, 'CHECKS.txt'), 'w').write(
        '# generated by build_all.py -- CGAL export (OpenSCAD 2021.01) + check_stl.py edge/manifold check\n' + '\n'.join(lines) + '\n')
    print('\n'.join(lines))
    return all(r['ok'] for r in res)


# camera: translate x,y,z, rot x,y,z, distance
CAM_PART = ['--viewall', '--autocenter', '--camera=0,0,0,55,0,25,0']
CAM_ASM = ['--camera=0,4,-8,28,0,-18,230']                       # same scale for every shape
CAM_BACKSIDE = ['--camera=0,12,-8,152,0,-18,285']
CAM_EXPL = ['--viewall', '--autocenter', '--camera=0,0,0,68,0,28,0']
CAM_SEC = ['--viewall', '--autocenter', '--camera=0,0,0,90,0,90,0']
CAM_DESK = ['--camera=0,6,40,72,0,28,250']
CAM_DESK_SEC = ['--viewall', '--autocenter', '--camera=0,0,0,90,0,90,0']


def build_png(jobs):
    os.makedirs(PNG, exist_ok=True)
    col = ['--colorscheme=Tomorrow', '--imgsize=900,760']
    todo = []
    for b in BOARDS:
        for s in SHAPES:
            for p in PARTS:
                todo.append((tag(b, s, p), b, s, p, (), ['--render'] + col + CAM_PART))
            todo.append((tag(b, s, 'assembly'), b, s, 'assembly', (), col + CAM_ASM))
            todo.append((tag(b, s, 'assembly_back'), b, s, 'assembly', (), col + CAM_BACKSIDE))
        todo.append((tag(b, 'coin', 'exploded'), b, 'coin', 'exploded', (), col + CAM_EXPL))
        todo.append((tag(b, 'coin', 'section'), b, 'coin', 'assembly', ('section=true',), col + CAM_SEC))
    todo.append((tag('1.43', 'coin', 'stand'), '1.43', 'coin', 'stand', (), ['--render'] + col + CAM_PART))
    todo.append((tag('1.43', 'coin', 'stand_under'), '1.43', 'coin', 'stand', (), ['--render'] + col + ['--viewall', '--autocenter', '--camera=0,0,0,140,0,20,0']))
    todo.append((tag('1.43', 'coin', 'desk'), '1.43', 'coin', 'desk', (), col + CAM_DESK))
    todo.append((tag('1.43', 'coin', 'desk_section'), '1.43', 'coin', 'desk', ('section=true',), col + CAM_DESK_SEC))
    with cf.ThreadPoolExecutor(jobs) as ex:
        futs = {ex.submit(scad, os.path.join(PNG, n + '.png'), b, s, p, d, png): n for (n, b, s, p, d, png) in todo}
        for f in cf.as_completed(futs):
            f.result(); print('  png', futs[f], flush=True)
    lineup()


def lineup():
    from PIL import Image, ImageDraw, ImageFont
    dims = {}
    try: dims = json.load(open(os.path.join(STL, 'dims.json')))
    except Exception: pass
    font = lambda n: ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', n)
    bold = lambda n: ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', n)
    cols = ['assembly', 'assembly_back', 'front', 'back', 'cap', 'lens']
    heads = ['asamblat (fata)', 'asamblat (spate)', 'FRONT (print)', 'BACK (print)', 'CAP', 'LENS']
    tw, th, lw, hh = 300, 253, 250, 58
    rows = [(b, s) for b in BOARDS for s in SHAPES]
    extra = [('1.43', 'coin', ['desk', 'desk_section', 'stand', 'stand_under', 'exploded', 'section']),
             ('1.75', 'coin', ['exploded', 'section'])]
    H = hh + th * (len(rows) + 1) + 60
    sheet = Image.new('RGB', (lw + tw * len(cols), H), 'white')
    d = ImageDraw.Draw(sheet)
    d.text((10, 8), 'SUFLET / Micul Smecher -- carcasa parametrica (OpenSCAD)', fill='black', font=bold(20))
    for j, h in enumerate(heads):
        d.text((lw + j * tw + 8, hh - 20), h, fill='#333', font=font(14))
    y = hh + 6
    for (b, s) in rows:
        dd = dims.get('%s_%s' % (b, s), {})
        d.text((10, y + 10), '%s  %s' % (b, s.upper()), fill='black', font=bold(20))
        if dd:
            d.text((10, y + 40), 'L x H x G [mm]', fill='#555', font=font(13))
            d.text((10, y + 58), '%.1f x %.1f x %.1f' % (float(dd['W']), float(dd['H']), float(dd['T'])), fill='black', font=font(15))
            d.text((10, y + 80), 'cu capac: H %.1f' % float(dd['H_with_cap']), fill='#555', font=font(13))
            d.text((10, y + 98), 'cu lentila: G %.1f' % float(dd['T_with_lens']), fill='#555', font=font(13))
            d.text((10, y + 116), 'difuzor: %s' % dd.get('spk', '?'), fill='#555', font=font(13))
        for j, c in enumerate(cols):
            f = os.path.join(PNG, tag(b, s, c) + '.png')
            if os.path.exists(f):
                im = Image.open(f).convert('RGB'); im.thumbnail((tw - 6, th - 6))
                sheet.paste(im, (lw + j * tw + 3, y))
        d.line((0, y + th - 2, sheet.width, y + th - 2), fill='#ddd')
        y += th
    # last row: desk stand + exploded + sections
    x = 10
    d.text((10, y + 4), 'extra:', fill='black', font=bold(16))
    cells = [(b, s, c) for (b, s, cs) in extra for c in cs]
    tw2 = (sheet.width - 20) // len(cells)
    for i, (b, s, c) in enumerate(cells):
        f = os.path.join(PNG, tag(b, s, c) + '.png')
        if os.path.exists(f):
            im = Image.open(f).convert('RGB'); im.thumbnail((tw2 - 4, th - 30))
            sheet.paste(im, (10 + i * tw2, y + 26))
            d.text((10 + i * tw2 + 4, y + 26 + im.height), '%s %s %s' % (b, s, c), fill='#333', font=font(12))
    sheet.save(os.path.join(PNG, 'lineup.png'))
    print('  png lineup.png', sheet.size)


if __name__ == '__main__':
    jobs = os.cpu_count() or 2
    if '-j' in sys.argv: jobs = int(sys.argv[sys.argv.index('-j') + 1])
    ok = True
    if '--png' not in sys.argv: ok = build_stl(jobs)
    if '--stl' not in sys.argv: build_png(jobs)
    sys.exit(0 if ok else 1)
