// =====================================================================================
//  SUFLET / MICUL SMECHER -- prototype enclosure ("Editia 0", hand-finished)   v1.1
//  Parametric OpenSCAD model (tested with OpenSCAD 2021.01). Build everything: python3 build_all.py
//
//  Parts:  front  = frosted clear shell (SLA), aperture + 0.8 mm lip over the cover glass,
//                   M2 heat-set/press-in insert bosses, cap stub, side cut-outs
//          back   = removable back cover (no glue: 3 x M2x4 Phillips into M2x3 inserts), battery bay,
//                   speaker pocket + grille (1.75), slide-switch cradle
//          cap    = "metal" cap for the tip (print + paint, later CNC Al), 1.6 mm ring hole
//          lens   = optional clear dome cabochon over the glass (0.3 mm air gap)
//          stand  = desk stand (Founders Desk Edition, USB powered): weighted pebble cradle,
//                   holds the amulet tilted back stand_tilt deg, USB-C plug pocket + cable channel
//          assembly / exploded / desk / board = views with a dummy board, battery, speaker
//                   (section = true cuts the views in half at x = 0 to check for collisions)
//
//  Frame: looking at the screen, +x right, +y up (towards the cap), +z towards the viewer.
//         z = 0 is the FRONT SURFACE OF THE COVER GLASS. "depth" = -z.
//  The board is always oriented with USB-C at 6 o'clock (bottom).
//  Shapes come from shapes.scad (generated by gen_shapes.py from the concept page).
// =====================================================================================

include <shapes.scad>

/* [Main] */
board = "1.75";        // ["1.75":Waveshare ESP32-S3-Touch-AMOLED-1.75 (voice), "1.43":Waveshare ESP32-S3-Touch-AMOLED-1.43]
shape = "coin";        // ["coin":Moneda, "drop":Lacrima, "gem":Cabochon, "cloud":Nor]
part  = "assembly";    // ["front","back","cap","lens","stand","assembly","exploded","desk","board"]
printer = "SLA";       // ["SLA":clear resin 0.05 mm, "FDM":PETG test fit]
tol_override = 0;      // >0 overrides the global fit clearance [mm]
spk_mode = "stack";    // ["stack":kit speaker behind battery (1.75), "none":no speaker (thinnest)]
use_lens_seat = true;  // 0.4 mm seat around the aperture for the optional dome lens
rim_pockets = true;    // hollow the rim outside the board (less resin, lighter)
board_screws = false;  // also screw the back cover posts into the board's own M2 standoffs
section = false;       // views only: cut away the x > 0 half
show_lens = false;     // views only: show the optional dome lens in "assembly"

/* [Shell] */
wall        = 1.8;   // side wall [mm] (1.6-2.0)
front_skin  = 1.0;   // resin in front of the glass surface
lip_overlap = 0.8;   // how far the lip covers the glass edge (radially)
back_t      = 2.0;   // back cover plate
rf_h = 3.0;  rf_v = 2.5;   // front edge round-over (horizontal x vertical)
rb_h = 1.0;  rb_v = 1.2;   // back edge round-over
ring_wall   = 1.2;   // wall around the board pocket when rim_pockets = true
rim_top     = 2.5;   // rim pockets start this deep below the glass front
shape_grow  = 1.00;  // >1 makes the silhouette bigger than the minimum that fits
squash_top  = 1.00;  // 0.6..1.0: shortens the silhouette ABOVE the screen (e.g. a shorter drop / gem)
nF = 8;              // round-over steps

/* [Battery] */
battery = true;  // false = USB-only build (Founders Desk Edition): no battery bay, thinner shell
bat_w = 25;      // across (x) -- 502535 default // UNVERIFIED -- measure your cell (25-26)
bat_l = 35;      // along (y), incl. protection PCB // UNVERIFIED -- measure (35-38 with PCM)
bat_t = 5.0;     // nominal thickness (real 502535 cells: 4.8-5.3) // UNVERIFIED -- measure
bat_clr = 0.3;   // pocket clearance in x/y
bat_foam = 0.8;  // foam / swelling gap (no glue!)

/* [Speaker (1.75)] */
spk_w = 20;  spk_l = 30;  spk_t = 5.5;   // Waveshare 8 ohm 2 W "2030" cavity speaker // UNVERIFIED for the kit version -- measure
spk_r = 9.5;                             // corner radius of the speaker outline // UNVERIFIED -- measure
spk_grille_w = 13; spk_grille_l = 17;    // sound area on the speaker face // UNVERIFIED -- measure
spk_clr = 0.3;

/* [Screws & inserts] */
insert_d     = 3.2;   // hole for M2x3 heat-set insert (Ruthex/CNC-Kitchen M2: 3.2); SLA: glue a press-in insert, hole = insert OD + 0.1
insert_depth = 4.0;   // hole depth (insert 3.0 + 1.0 for melt/glue)
boss_gap     = 0.8;   // resin between insert hole and board pocket
boss_r       = 2.8;   // boss outer radius
screw_d      = 2.4;   // M2 clearance through the back cover
head_d       = 4.2;   // counterbore for M2 pan/cheese head (DIN 7985 head 4.0 x 1.6)
head_h       = 1.2;   // counterbore depth (head sits ~0.4 proud of a 1.6 head; use DIN 965 countersunk to be flush)
skirt_h      = 1.5;   // locating skirt of the back cover
skirt_t      = 0.8;
post_d       = 4.0;   // posts that press the board standoffs from behind
post_gap     = 0.3;   // gap to standoff -> 0.5 mm EVA foam dot

/* [Slide switch MSK-12C02] */
sw_body = [7.0, 3.0, 1.5];    // L x W x H body // UNVERIFIED -- measure your batch
sw_act  = [1.0, 1.0, 1.5];    // actuator L x W x protrusion // UNVERIFIED -- measure
sw_travel = 1.5;              // UNVERIFIED -- measure

/* [Cap + ring] */
stub_r = 3.0;  stub_h = 3.5;  stub_embed = 2.5;
cap_wall = 1.6;  cap_top = 1.8;  cap_sink = 2.2;
ear_t = 2.6;  ear_w = 5.0;  ear_h = 4.2;  ring_hole_d = 1.6;   // 12 mm split ring
setscrew_d = 1.6;             // tap M2 (or glue only)
glue_gap = 0.1;

/* [Dome lens] */
lens_gap = 0.3;  lens_recess = 0.4;  lens_flange = 1.6;  lens_flange_t = 0.8;  lens_dome_h = 2.5;

/* [Desk stand (Founders Desk Edition)] */
stand_tilt     = 15;    // screen leans back this much from vertical [deg]
stand_plug_len = 16;    // USB-C plug body left OUTSIDE the shell (overmold + strain relief) // UNVERIFIED -- measure your cable
stand_cable_d  = 4.5;   // cable diameter // UNVERIFIED -- measure your cable
stand_bend     = 7;     // height left under the plug for the cable to bend towards the back
stand_clr      = 0.4;   // extra clearance shell <-> cradle (on top of tol)
stand_wall     = 2.4;   // cradle wall
stand_front_h  = 4.0;   // front lip height above the lowest point of the shell (must stay below the glass)
stand_back_h   = 10.0;  // back support height (stays below the back-cover screw heads)
stand_sink     = 9;     // how deep the shell sinks into the pebble (at the centre)
stand_ry       = 28;    // half depth of the pebble (front-back)
stand_rx_min   = 36;    // minimum half width of the pebble
stand_weight_d = 20.6;  // ballast pockets from below (fill with steel shot / 4.5 mm steel BBs + epoxy)
stand_weight_h = 12.5;  // pocket depth (pockets are clipped so they never break into the cradle or the plug pocket)

/* [Render] */
fn_big = 144;
$fn = 48;

// =====================================================================================
//  BOARD DATA -- model frame (USB-C down). Sources: Waveshare STEP + drawing PDFs.
//  1.75: ESP32-S3-Touch-AMOLED-1_75.stp / ESP32-S3-Touch-AMOLED-1.75.pdf (2025-03-24)
//        STEP -> model: x = Z_step, y = X_step, depth = 2.77 - Y_step
//  1.43: ESP32-S3-Touch-AMOLED-1_43.stp (2024-12-09), rotated +90 deg (native USB at 9 o'clock)
//        STEP -> model: x = -Y_step, y = X_step, depth = 1.10 - Z_step
// =====================================================================================
is175 = board == "1.75";
tol = tol_override > 0 ? tol_override : (printer == "FDM" ? 0.3 : 0.2);

glass_r      = is175 ? 24.48 : 23.00;   // cover glass (TP OD 48.96 / 46.00)            verified STEP
glass_t      = 1.10;                    // verified
glass_flat_r = is175 ? 22.08 : 21.50;   // flat front of the glass                       1.75 verified / 1.43 from DXF notes
glass_cd     = is175 ? 0.50  : 0.70;    // height of the rounded/chamfered glass edge     verified STEP
view_r       = is175 ? 21.88 : 18.375;  // active / touch area                            verified
body_r       = is175 ? 23.00 : 21.75;   // display module + PCB radius                    verified
pcb_d        = is175 ? [5.70, 6.90] : [5.00, 6.20];   // PCB front/back depth            verified
so_pos       = is175 ? [[14.70,13.75],[14.70,-13.75],[-20.50,0]]
                     : [[15.75,11.55],[15.75,-11.55],[-15.75,11.55],[-15.75,-11.55]];     // M2 SMT standoffs, verified
so_depth     = is175 ? 10.43 : 10.22;   // standoff end (M2 female thread)               verified
usb_face_r   = is175 ? 23.80 : 22.46;   // receptacle face                               verified
usb_depth    = is175 ? 8.55  : 7.87;    // tongue centre                                  verified (+-0.3)
usb_cut_w    = 12.4;                    // cable overmold clearance // UNVERIFIED -- measure your USB-C cable plug
usb_cut_h    = 7.0;                     // UNVERIFIED -- measure your USB-C cable plug
tall_edge    = is175 ? 12.70 : 10.70;   // 1.75: 8-pin header at x=+18.7; 1.43: 2x7 headers  verified
bat_floor    = is175 ? 8.90  : 10.00;   // deepest part under the battery footprint + 0.2   verified from STEP
bat_c        = is175 ? [0, 1.6] : [0, 0];     // battery centre (keeps 1.75 cell clear of USB-C)
sw_pos       = is175 ? [-16.5, -12.5] : [16.5, -3.0];   // slide switch (near BAT connector)
// side buttons: [label, origin xy, direction deg, depth, hole d]
btns = is175 ? [["PWR",  [-11.31, 17.20], 123.3, 7.60, 2.6],   // PWR (AXP2101 PWRON) upper-left  verified STEP + photo
                ["BOOT", [ 11.31, 17.10],  56.5, 7.60, 1.6]]   // BOOT upper-right
             : [["BOOT/RST", [-18.43,  8.01], 156.5, 7.85, 1.6],  // radial side keys, actuator d2.0 tip r=20.97,
                ["BOOT/RST", [-18.43, -8.01], 203.5, 7.85, 1.6]]; // depth 7.85: verified STEP. Which one is BOOT: // UNVERIFIED -- check silkscreen
// microphones (1.75 only): [origin xy, direction deg, depth]; port direction // UNVERIFIED -- top-port assumed
mics = is175 ? [[[-10.96,-17.54], 238.0, 7.5], [[11.74,-17.35], 304.1, 7.5]] : [];
mic_hole_d = 1.0;
spk_on = is175 && spk_mode == "stack";

// =====================================================================================
//  DERIVED
// =====================================================================================
S       = shape_data(shape);
S0_pts  = S[2];
// optional squash of the upper half (y > 0) -- keeps normals / curvature / bosses consistent
S_pts   = [for (p = S0_pts) p[1] > 0 ? [p[0], p[1] * squash_top] : p];
S_nrm   = [for (i = [0:len(S0_pts) - 1]) let(n = S[3][i])
             S0_pts[i][1] > 0 ? [n[0], n[1] / squash_top] / norm([n[0], n[1] / squash_top]) : n];
S_rho   = [for (i = [0:len(S0_pts) - 1]) S0_pts[i][1] > 0 ? S[4][i] * squash_top : S[4][i]];
S_dmin  = min(S[5], min([for (p = S_pts) norm(p)]));
S_tip   = [S[6][0], S[6][1] * squash_top];
S_boss  = [for (b = S[7]) [b[0], (b[0] > 0 && b[0] < 180) ? b[1] * squash_top : b[1]]];
S_bbox  = [min([for (p = S_pts) p[0]]), max([for (p = S_pts) p[0]]), min([for (p = S_pts) p[1]]), max([for (p = S_pts) p[1]])];

Rc      = glass_r + tol;                           // board pocket radius
r_ap    = glass_r - lip_overlap;                   // aperture radius
z_ap    = -glass_cd * (1 - (lip_overlap + tol) / (glass_r - glass_flat_r));   // lip underside at aperture edge
z_front = front_skin;

function inset_front(z) = z <= z_front - rf_v ? 0 : rf_h * (1 - cos(asin(min(1, (z - (z_front - rf_v)) / rf_v))));

bat_top = battery ? bat_floor + bat_t + bat_foam : 0;
D_open  = usb_depth + usb_cut_h / 2 + 0.6;         // cavity may widen behind this depth
D_in    = max(spk_on ? max(bat_top, bat_floor) + spk_t + spk_clr : bat_top, tall_edge + 0.3, D_open + skirt_h + 0.5);
z_split = -D_in;
z_back  = -(D_in + back_t);
z_mid   = (z_front + z_back) / 2;
T_total = z_front - z_back;

r_b     = Rc + boss_gap + insert_d / 2;            // boss centre radius
need_boss = r_b + max(boss_r, head_d / 2 + rb_h + 0.2);
k_wall  = (Rc + wall + inset_front(-glass_cd) + 0.2) / S_dmin;
k_boss  = max([for (b = S_boss) need_boss / b[1]]);
k       = max(k_wall, k_boss) * shape_grow;        // mm per concept unit

Pm      = [for (p = S_pts) k * p];                 // outline [mm]
tipm    = k * S_tip;
bossP   = [for (b = S_boss) r_b * [cos(b[0]), sin(b[0])]];
W       = k * (S_bbox[1] - S_bbox[0]);
H       = k * (S_bbox[3] - S_bbox[2]);

r_lens  = r_ap + lens_flange;
r_seat  = r_lens + tol;
z_seat  = use_lens_seat ? z_front - lens_recess : z_front;

echo(str("MS_DIMS board=", board, " shape=", shape, " spk=", spk_on ? "stack" : "none", " tol=", tol,
         " k=", k, " W=", W, " H=", H, " T=", T_total, " H_with_cap=", H + stub_h + cap_top + ear_h,
         " T_with_lens=", T_total + (z_seat + lens_flange_t + lens_dome_h - z_front),
         " D_in=", D_in, " split_z=", z_split, " bosses=", [for (b = S_boss) b[0]]));

// =====================================================================================
//  GEOMETRY HELPERS
// =====================================================================================
function ring(ins) = [for (i = [0:len(S_pts) - 1])
    let(d = min(ins, 0.85 * k * S_rho[i])) [Pm[i][0] - S_nrm[i][0] * d, Pm[i][1] - S_nrm[i][1] * d]];

// closed loft through levels [[z, inset], ...] (z ascending)
module loft(levels) {
    n = len(S_pts); m = len(levels);
    pts = [for (l = levels) for (p = ring(l[1])) [p[0], p[1], l[0]]];
    side = [for (j = [0:m - 2]) for (i = [0:n - 1]) each [
        [j*n + i, (j+1)*n + i, (j+1)*n + (i+1) % n],
        [j*n + i, (j+1)*n + (i+1) % n, j*n + (i+1) % n]]];
    bottom = [[for (i = [0:n - 1]) i]];
    top    = [[for (i = [n - 1:-1:0]) (m - 1) * n + i]];
    polyhedron(points = pts, faces = concat(side, bottom, top), convexity = 6);
}

function ray_t(P, o, d) = max(concat([0], [for (i = [0:len(P) - 1])
    let(a = P[i], b = P[(i + 1) % len(P)], e = b - a, den = d[0] * e[1] - d[1] * e[0])
    if (abs(den) > 1e-12)
    let(t = ((a[0] - o[0]) * e[1] - (a[1] - o[1]) * e[0]) / den,
        u = ((a[0] - o[0]) * d[1] - (a[1] - o[1]) * d[0]) / den)
    if (t > 0 && u >= -1e-9 && u <= 1 + 1e-9) t]));

module outline2d() polygon(Pm);
module inner2d() offset(r = -wall) outline2d();
module boss_discs2d(extra = 0) for (p = bossP) translate(p) circle(r = boss_r + extra);
module stub_keep2d() translate([tipm[0] - stub_r - 1.5, tipm[1] - stub_embed - 1.2]) square([2 * stub_r + 3, 30]);
module rim_open2d(extra = 0) difference() { inner2d(); boss_discs2d(extra); stub_keep2d(); }
module rim_pocket2d() difference() { rim_open2d(); circle(r = Rc + ring_wall, $fn = fn_big); }
module stadium2d(w, h) hull() { for (s = [-1, 1]) translate([s * (w - h) / 2, 0]) circle(d = h); }
module rrect2d(w, l, r) offset(r = r) square([max(0.01, w - 2 * r), max(0.01, l - 2 * r)], center = true);
module zslab(z0, z1) translate([0, 0, z0]) linear_extrude(z1 - z0, convexity = 6) children();

// =====================================================================================
//  FRONT SHELL
// =====================================================================================
module body_front() loft(concat([[z_split, 0]],
    [for (i = [0:nF]) let(th = 90 * i / nF) [z_front - rf_v + rf_v * sin(th), rf_h * (1 - cos(th))]]));

module body_back() loft(concat(
    [for (i = [0:nF / 2]) let(th = 90 * i / (nF / 2)) [z_back + rb_v - rb_v * cos(th), rb_h * (1 - sin(th))]],
    [[z_split, 0]]));

// glass-hugging pocket + aperture + lens seat
module board_pocket() {
    af = 0.4;  // aperture edge round
    rotate_extrude($fn = fn_big) polygon(concat(
        [[0, z_split - 1], [Rc, z_split - 1], [Rc, -glass_cd], [r_ap, z_ap]],
        [for (i = [0:6]) let(a = 180 - 90 * i / 6) [r_ap + af + af * cos(a), z_seat - af + af * sin(a)]],
        [[r_ap + af, z_front + 2], [0, z_front + 2]]));
    if (use_lens_seat) zslab(z_seat, z_front + 2) circle(r = r_seat, $fn = fn_big);
}

module stub() translate([tipm[0], tipm[1] - stub_embed, z_mid]) rotate([-90, 0, 0])
    difference() {
        cylinder(r = stub_r, h = stub_embed + stub_h);
        // set-screw dimple on the back side (-z of the shell = +y local)
        translate([0, stub_r, stub_embed + stub_h / 2]) rotate([90, 0, 0]) cylinder(d = 1.4, h = 1.2, center = true);
    }

module side_cuts() {
    // USB-C (cable overmold)
    translate([0, 0, -usb_depth]) rotate([90, 0, 0]) linear_extrude(80) stadium2d(usb_cut_w, usb_cut_h);
    // buttons / pin holes, with an outer countersink
    for (b = btns) let(o = b[1], a = b[2], d = [cos(a), sin(a)], t = ray_t(Pm, o, d))
        translate([o[0], o[1], -b[3]]) rotate([0, 0, a]) rotate([0, 90, 0]) {
            cylinder(d = b[4], h = t + 5);
            translate([0, 0, t - 0.9]) cylinder(d1 = b[4], d2 = b[4] + 2.2, h = 1.2);
        }
    // microphones
    for (m = mics) let(o = m[0], a = m[1], d = [cos(a), sin(a)], t = ray_t(Pm, o, d))
        translate([o[0], o[1], -m[2]]) rotate([0, 0, a]) rotate([0, 90, 0]) {
            cylinder(d = mic_hole_d, h = t + 5, $fn = 24);
            translate([0, 0, t - 0.6]) cylinder(d1 = mic_hole_d, d2 = mic_hole_d + 1.2, h = 0.8, $fn = 24);
        }
}

module front_shell() difference() {
    union() { body_front(); stub(); }
    board_pocket();
    zslab(z_split - 1, -D_open) rim_open2d();
    if (rim_pockets) zslab(z_split - 1, -rim_top) rim_pocket2d();
    side_cuts();
    // insert holes (with a 0.4 mm lead-in chamfer)
    for (p = bossP) translate([p[0], p[1], z_split - 0.01]) {
        cylinder(d = insert_d, h = insert_depth + 0.01);
        cylinder(d1 = insert_d + 0.8, d2 = insert_d, h = 0.4);
    }
}

// =====================================================================================
//  BACK COVER
// =====================================================================================
module bat_brackets(h) {   // 4 corner "L" brackets: hold the cell, let the wires out anywhere
    bw = bat_w + 2 * bat_clr; bl = bat_l + 2 * bat_clr; t = 0.8; L = 6;
    translate([bat_c[0], bat_c[1], z_split - 0.01]) for (sx = [-1, 1], sy = [-1, 1])
        translate([sx * bw / 2, sy * bl / 2, 0]) linear_extrude(h + 0.01) {
            translate([sx > 0 ? 0 : -t, sy > 0 ? -L + t : -t]) square([t, L]);
            translate([sx > 0 ? -L + t : -t, sy > 0 ? 0 : -t]) square([L, t]);
        }
}

module spk_pocket() {
    sw = spk_w + 2 * spk_clr; sl = spk_l + 2 * spk_clr;
    translate([bat_c[0], bat_c[1], z_split - 0.01]) linear_extrude(spk_t * 0.6)
        difference() { rrect2d(sw + 1.6, sl + 1.6, min(spk_r + 0.8, (sw + 1.6) / 2 - 0.01));
                       rrect2d(sw, sl, min(spk_r, sw / 2 - 0.01));
                       // wire exit at the bottom end
                       translate([0, -sl / 2]) square([5, 4], center = true); }
}

module grille_holes() {
    hd = 1.3; p = 2.1;
    translate([bat_c[0], bat_c[1], z_back - 1]) linear_extrude(back_t + 2)
        intersection() {
            rrect2d(spk_grille_w, spk_grille_l, 3);
            for (i = [-10:10], j = [-10:10]) translate([i * p + (j % 2 == 0 ? 0 : p / 2), j * p * 0.866]) circle(d = hd, $fn = 16);
        }
}

module switch_cradle() {
    b = sw_body + [2 * 0.15, 2 * 0.15, 0];
    translate([sw_pos[0], sw_pos[1], z_split - 0.01]) linear_extrude(b[2] + 0.01)
        difference() { square([b[1] + 1.6, b[0] + 1.6], center = true); square([b[1], b[0]], center = true);
                       square([b[1] + 4, 3], center = true); }   // side openings for the wires
}
module switch_slot() {
    sl = sw_travel + sw_act[0] + 2 * tol; sw = sw_act[1] + 2 * tol;
    translate([sw_pos[0], sw_pos[1], z_back - 1]) linear_extrude(back_t + 2) square([sw, sl], center = true);
    // outside recess so the actuator stands 0.3 proud of the recess floor
    rec = max(0, back_t - (sw_act[2] - 0.3));
    translate([sw_pos[0], sw_pos[1], z_back - 1]) linear_extrude(1 + rec) rrect2d(sw + 3.0, sl + 3.0, 1.0);
}

module posts() for (p = so_pos) {
    h = D_in - so_depth - post_gap;
    translate([p[0], p[1], z_split - 0.01]) difference() {
        cylinder(d = post_d, h = h + 0.01);
        if (board_screws) translate([0, 0, -1]) cylinder(d = screw_d, h = h + 2);
    }
}

module back_cover() difference() {
    union() {
        body_back();
        // locating skirt following the cavity wall
        zslab(z_split - 0.01, z_split + skirt_h) difference() {
            offset(delta = -tol) rim_open2d(tol);
            offset(delta = -tol - skirt_t) rim_open2d(tol);
        }
        if (battery) bat_brackets((spk_on ? spk_t + spk_clr : 0) + bat_foam + bat_t * 0.5);
        if (spk_on) spk_pocket();
        switch_cradle();
        posts();
    }
    for (p = bossP) translate([p[0], p[1], z_back - 1]) {
        cylinder(d = screw_d, h = back_t + 3);
        cylinder(d = head_d, h = 1 + head_h);
    }
    if (board_screws) for (p = so_pos) translate([p[0], p[1], z_back - 1]) {
        cylinder(d = screw_d, h = back_t + 3); cylinder(d = head_d, h = 1 + head_h); }
    if (spk_on) grille_holes();
    switch_slot();
}

// =====================================================================================
//  CAP (tip) -- built in a local frame (local z = along the stub, origin at stub base = tip)
// =====================================================================================
cap_r = stub_r + cap_wall;
cap_len = stub_h + cap_top;
module cap_local() difference() {
    union() {
        // body with a rounded top
        rotate_extrude() polygon(concat([[0, -cap_sink], [cap_r, -cap_sink]],
            [for (i = [0:8]) let(a = 90 * i / 8) [cap_r - 1.4 + 1.4 * cos(a), cap_len - 1.4 + 1.4 * sin(a)]],
            [[0, cap_len]]));
        // ear for the split ring (hole along x -> ring hangs in the face plane)
        hull() {
            translate([-ear_t / 2, -ear_w / 2, cap_len - 1.0]) cube([ear_t, ear_w, 0.1]);
            translate([0, 0, cap_len + ear_h - ear_w / 2]) rotate([0, 90, 0]) cylinder(d = ear_w, h = ear_t, center = true);
        }
    }
    translate([0, 0, -cap_sink - 1]) cylinder(r = stub_r + glue_gap + tol / 2, h = cap_sink + stub_h + 1.2);
    translate([0, 0, cap_len + ear_h - ear_w / 2]) rotate([0, 90, 0]) cylinder(d = ring_hole_d, h = ear_t + 2, center = true, $fn = 24);
    // set screw (M2, from the back side of the shell)
    translate([0, 0, stub_h / 2]) rotate([-90, 0, 0]) cylinder(d = setscrew_d, h = cap_r + 1, $fn = 20);
}
module cap_place() translate([tipm[0], tipm[1], z_mid]) rotate([-90, 0, 0]) children();
module cap_in_shell() difference() {
    cap_place() cap_local();
    // saddle: follow the shell outline exactly
    translate([0, 0, z_back - 5]) linear_extrude(T_total + 10) offset(delta = glue_gap) outline2d();
}

// =====================================================================================
//  LENS
// =====================================================================================
module lens() {
    zf = z_seat; R = (r_lens * r_lens + lens_dome_h * lens_dome_h) / (2 * lens_dome_h);
    union() {
        translate([0, 0, lens_gap]) cylinder(r = r_ap - 1.0, h = zf - lens_gap + 0.01, $fn = fn_big);
        translate([0, 0, zf]) cylinder(r = r_lens, h = lens_flange_t, $fn = fn_big);
        intersection() {
            translate([0, 0, zf + lens_flange_t + lens_dome_h - R]) sphere(r = R, $fn = fn_big * 2);
            translate([0, 0, zf + lens_flange_t]) cylinder(r = r_lens, h = lens_dome_h + 1, $fn = fn_big);
        }
    }
}

// =====================================================================================
//  DESK STAND (Founders Desk Edition, USB powered)
//  World frame of the stand: X right, Y away from the viewer, Z up, table at Z = 0.
//  The amulet stands on its bottom edge (USB-C at 6 o'clock), leaning back stand_tilt deg;
//  the cable plug goes straight down into a pocket and the cable leaves through a channel
//  in the underside towards the back. Printed as is (bottom on the bed).
// =====================================================================================
st_yb  = k * S_bbox[2];                   // lowest point of the outline (on x = 0 for every shape)
st_c   = tol + stand_clr;                 // clearance shell <-> cradle
st_a   = 90 - stand_tilt;                 // model -> world rotation about X
st_u   = -usb_depth - z_mid;              // plug axis, model z relative to the shell mid-plane
st_hc  = stand_bend + stand_plug_len * sin(st_a) - st_u * cos(st_a);   // height of the bottom-centre line
st_rx  = max(stand_rx_min, W / 2 + 6);
st_yc  = -st_yb * cos(st_a) * 0.5;        // base centre (between the screen and the centre of mass)
st_t   = (st_hc + st_u * cos(st_a)) / sin(st_a);          // plug axis length down to the table
st_yex = -st_t * cos(st_a) - st_u * sin(st_a);            // where the plug axis meets the table (world Y)

module st_place() translate([0, 0, st_hc]) rotate([st_a, 0, 0]) translate([0, -st_yb, -z_mid]) children();

// shell envelope (+ clearance + extra), swept upwards so the cradle never traps it (model frame)
module st_env(extra = 0) let(c = st_c + extra) {
    zslab(z_back - c, z_front + c) hull() { offset(r = c) outline2d(); translate([0, 300]) offset(r = c) outline2d(); }
    // back-cover screw heads stand ~0.4 mm proud
    for (p = bossP) translate([p[0], p[1], z_back - c - 1.5]) cylinder(d = head_d + 1 + 2 * extra, h = 2);
}
module st_plug(extra = 0) translate([0, st_yb + 3, -usb_depth]) rotate([90, 0, 0])
    linear_extrude(300) stadium2d(usb_cut_w + 2 * (st_c + extra), usb_cut_h + 2 * (st_c + extra));

module st_cup() {   // model frame
    zb = z_back - st_c - stand_wall; zf = z_front + st_c + stand_wall;
    intersection() {
        zslab(zb, zf) offset(r = st_c + stand_wall) outline2d();
        union() {
            translate([-500, st_yb - 50, zb - 1]) cube([1000, 50 + stand_back_h, z_mid - zb + 1]);
            translate([-500, st_yb - 50, z_mid - 0.01]) cube([1000, 50 + stand_front_h, zf - z_mid + 1.01]);
        }
    }
}

// one monolithic "river stone": a squashed ellipsoid cut below its equator; the shell sinks into it
st_hz = st_hc + stand_sink;               // pebble height at its centre
st_z0 = 0.45 * st_hz;                     // ellipsoid centre below the table -> sloped flanks
module st_dome(inset = 0) translate([0, st_yc, -st_z0])
    scale([st_rx - inset, stand_ry - inset, st_hz + st_z0 - inset]) sphere(r = 1, $fn = 128);
module st_body() intersection() {
    st_dome();
    translate([-500, -500, 0]) cube([1000, 1000, 500]);
}

module stand() difference() {
    st_body();
    st_place() {
        st_env();
        st_plug();
        // keep the screen free: nothing in front of the shell above the front lip, nothing above the back support
        translate([-500, st_yb + stand_front_h, z_mid]) cube([1000, 300, 300]);
        translate([-500, st_yb + stand_back_h, -300]) cube([1000, 300, 600]);
    }
    // cable: bend chamber under the plug, then a channel to the back (both open to the table)
    cw = stand_cable_d + 1.0;
    translate([-cw / 2, st_yex - 4, -1]) cube([cw, 16, stand_bend + 1]);
    translate([-cw / 2, st_yex, -1]) cube([cw, 200, stand_cable_d + 1.0]);
    // weight pockets (from below), kept >= 1.6 mm away from the cradle and the plug pocket
    for (sx = [-1, 1]) difference() {
        intersection() {
            translate([sx * st_rx * 0.45, st_yc, -1]) cylinder(d = stand_weight_d, h = stand_weight_h + 1, $fn = 72);
            st_dome(2.0);
        }
        st_place() st_env(1.6);
        st_place() st_plug(1.6);
        translate([-cw / 2 - 1.6, -200, -2]) cube([cw + 3.2, 400, 100]);
    }
}

// =====================================================================================
//  DUMMY BOARD, BATTERY, SPEAKER (for views only)
// =====================================================================================
// the default face (Face.h: eyeW 0.12, eyeH 0.19, spacing 0.19, cy +0.02 down, lidTop 0.19,
// lidTilt 0.16 rad = inner corners lower, highlight upper-right) -- decoration for the views only
module eye2d(sd, part = "body") let(D = 2 * view_r, ex = sd * 0.19 * D, ey = -0.02 * D, rx = 0.12 * D, ry = 0.19 * D,
                                    kk = tan(0.16 * 180 / PI) * (-sd), yl = ey + (1 - 2 * 0.19) * ry)
    intersection() {
        if (part == "body") translate([ex, ey]) scale([rx, ry]) circle(r = 1, $fn = 72);
        else if (part == "glow") translate([ex, ey]) scale([rx + 0.035 * D, ry + 0.035 * D]) circle(r = 1, $fn = 72);
        else translate([ex + 0.22 * rx, ey + 0.12 * ry]) scale([0.34 * rx, 0.46 * ry]) circle(r = 1, $fn = 48);
        polygon([[ex - D, yl + kk * D + (part == "glow" ? 0.035 * D : 0)], [ex + D, yl - kk * D + (part == "glow" ? 0.035 * D : 0)],
                 [ex + D, ey - 2 * D], [ex - D, ey - 2 * D]]);
    }
module dummy_eyes() for (sd = [-1, 1]) {
    color("#fff0c8", 0.28) translate([0, 0, 0.005]) linear_extrude(0.01) eye2d(sd, "glow");
    color("#fff0c8") translate([0, 0, 0.01]) linear_extrude(0.02) eye2d(sd, "body");
    color("#ffffff") translate([0, 0, 0.03]) linear_extrude(0.02) eye2d(sd, "hl");
}

module dummy_board() {
    if (!section) dummy_eyes();
    color("#101216") cutd() rotate_extrude($fn = fn_big) polygon([[0, 0], [glass_flat_r, 0], [glass_r, -glass_cd], [glass_r, -glass_t], [0, -glass_t]]);
    color("#1d1f24") cutd() translate([0, 0, -pcb_d[0]]) cylinder(r = body_r - 0.1, h = pcb_d[0] - glass_t, $fn = fn_big);
    color("#1f5fa8") cutd() translate([0, 0, -pcb_d[1]]) cylinder(r = body_r, h = pcb_d[1] - pcb_d[0], $fn = fn_big);
    color("#c9a54a") cutd() for (p = so_pos) translate([p[0], p[1], -so_depth]) cylinder(d = 3.5, h = so_depth - pcb_d[1]);
    color("#b8bcc4") cutd() translate([-4.47, -usb_face_r, -usb_depth - 1.63]) cube([8.94, 7.5, 3.26]);
    color("#222") cutd() if (is175) {
        translate([17.48, -10.43, -12.7]) cube([2.4, 20.86, 12.7 - pcb_d[1]]);           // 8-pin header
        for (y = [2.67, -10.63]) translate([-20.12, y, -11.7]) cube([4.2, 7.65, 4.8]);  // SPK / BAT
    } else {
        for (s = [-1, 1]) translate([s > 0 ? 14 : -18.5, -4.6, -10.7]) cube([4.5, 9.2, 10.7 - pcb_d[1]]);
    }
    color("#e8e8e8") cutd() for (b = btns) translate([b[1][0], b[1][1], -b[3]]) rotate([0, 0, b[2]]) cube([4, 4, 2], center = true);
}
module dummy_battery() if (battery) color("#8fb4d9") cutd() translate([bat_c[0], bat_c[1], z_split + (spk_on ? spk_t + spk_clr : 0) + bat_foam + bat_t / 2])
    cube([bat_w, bat_l, bat_t], center = true);
module dummy_speaker() if (spk_on) color("#2a2c31") cutd() translate([bat_c[0], bat_c[1], z_split]) linear_extrude(spk_t) rrect2d(spk_w, spk_l, spk_r);
module dummy_switch() color("#d0d0d0") cutd() translate([sw_pos[0], sw_pos[1], z_split + sw_body[2] / 2]) cube([sw_body[1], sw_body[0], sw_body[2]], center = true);

// =====================================================================================
//  OUTPUT
// =====================================================================================
// views: render() avoids OpenCSG artefacts of the big subtracted helper volumes; colour goes outside render()
module cutx() if (section) render() intersection() { children(); translate([-200, -200, -200]) cube([200, 400, 400]); } else render() children();
module cutd() if (section) render() intersection() { children(); translate([-200, -200, -200]) cube([200, 400, 400]); } else children();
module view_front()  color("#dfe9f5", 0.55) cutx() front_shell();
module view_back()   color("#cfd8e3") cutx() back_cover();
module view_cap()    color("#b9bcc2") cutx() cap_in_shell();
module view_lens()   color("#f4f8ff", 0.16) cutx() lens();
module view_inner()  { dummy_board(); dummy_battery(); dummy_speaker(); dummy_switch(); }
module view_stand()  color("#e9e4da") cutx() stand();

echo(str("MS_STAND tilt=", stand_tilt, " base=", 2 * st_rx * sqrt(1 - pow(st_z0 / (st_hz + st_z0), 2)), "x",
         2 * stand_ry * sqrt(1 - pow(st_z0 / (st_hz + st_z0), 2)), " pebble_h=", st_hz, " shell_bottom_z=", st_hc,
         " total_height~", st_hc + H * sin(st_a) + (T_total / 2) * cos(st_a)));

if (part == "front")      translate([0, 0, z_front]) rotate([180, 0, 0]) front_shell();       // print face-down
else if (part == "back")  translate([0, 0, -z_back]) back_cover();                             // outer face on the bed
else if (part == "cap")   translate([0, 0, cap_sink]) rotate([90, 0, 0]) translate([-tipm[0], -tipm[1], -z_mid]) cap_in_shell();
else if (part == "lens")  translate([0, 0, -lens_gap]) lens();
else if (part == "stand") stand();                                                               // bottom on the bed
else if (part == "desk")  { view_stand(); st_place() { view_front(); view_cap(); view_inner(); view_back(); } }
else if (part == "board") { dummy_board(); dummy_battery(); dummy_speaker(); }
else if (part == "exploded") {
    e1 = D_in + 8; e2 = e1 + 6 + (battery ? bat_t : 0); e3 = e2 + 10;
    translate([0, 0, 14]) view_lens();
    view_front();
    translate([0, 22, 0]) view_cap();
    translate([0, 0, -e1]) dummy_board();
    translate([0, 0, -e2]) dummy_battery();
    translate([0, 0, -e3]) { dummy_speaker(); dummy_switch(); view_back(); }
}
else { // assembly
    view_front(); view_cap(); view_inner(); view_back();
    if (show_lens) %cutx() lens();   // background modifier: drawn see-through (a coloured transparent lens hides the screen in preview)
}
