#!/usr/bin/env python3
"""Inline eyes/eyes.js and eyes/designs.js into os/index.html (between the SOUL-EYES markers),
then copy the page to site/os.html so both stay byte-identical. Run after changing the eye engine."""
import pathlib, re
root = pathlib.Path(__file__).resolve().parents[2]
page = root / "os" / "index.html"
eyes = (root / "eyes" / "eyes.js").read_text()
designs = (root / "eyes" / "designs.js").read_text()
assert "</script" not in eyes and "</script" not in designs
block = ("<!-- SOUL-EYES:BEGIN (generated by os/tools/inline_eyes.py from eyes/eyes.js + eyes/designs.js; do not edit here) -->\n"
         f"<script>\n{eyes.rstrip()}\n</script>\n<script>\n{designs.rstrip()}\n</script>\n<!-- SOUL-EYES:END -->")
s = page.read_text()
if "<!-- SOUL-EYES:BEGIN" in s:
    s = re.sub(r"<!-- SOUL-EYES:BEGIN.*?<!-- SOUL-EYES:END -->", lambda m: block, s, flags=re.S)
else:
    s = s.replace("\n<script>\n\"use strict\";", "\n" + block + "\n<script>\n\"use strict\";", 1)
page.write_text(s)
(root / "site" / "os.html").write_text(s)
print("inlined", len(eyes), "+", len(designs), "bytes ->", page, "and site/os.html")
