#!/usr/bin/env python3
"""Build micul-smecher/dist/SOUL-package.zip from the vault folder.

    python3 docs/_tools/build_zip.py            # from micul-smecher/

Rules: no build dirs or caches (.pio, __pycache__, .pytest_cache, data/, .venv, cad/cache), no screenshots in site/,
and any single file whose deflated size exceeds MAX_DEFLATED is skipped and listed in SKIPPED.txt inside the zip.
"""
import fnmatch
import os
import zipfile
import zlib

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
DIST = os.path.join(ROOT, 'dist')
ZIP = os.path.join(DIST, 'SOUL-package.zip')
PREFIX = 'SOUL-package/'
MAX_DEFLATED = 10 * 1024 * 1024      # skip single files that stay > 10 MB compressed
SKIP_DIRS = {'.pio', '__pycache__', '.pytest_cache', '.venv', 'venv', 'node_modules', 'cache', 'data', '.git'}

# (folder, include patterns, recursive)
SPEC = [
    ('docs', ['*'], True),
    ('firmware', ['*'], True),
    ('ai', ['*'], True),
    ('os', ['index.html', 'SPEC.md', 'ARCHITECTURE.md'], False),
    ('site', ['*'], True),                         # screenshots excluded below
    ('prototip', ['README*', 'COMANDA*', '*.md'], False),
    ('prototip/stl', ['*'], True),
    ('prototip/step', ['*'], True),
    ('prototip/cad', ['*.py', '*.json', '*.txt'], False),
    ('prototip/img', ['*.png'], True),
    ('blueprints', ['*.png', '*.svg', 'README.md'], True),
    ('renders/v8', ['*.png', '*.gif', '*.mp4', 'README.md'], False),   # final design, size M
    ('renders/v6', ['README.md'], False),          # CMF + hex colours
    ('brand/logo', ['*'], True),
    ('research', ['*.md'], True),                  # so the links in docs/ work
    ('investors', ['*'], True),                    # incl. poc-1.1 official annexes
]
EXCLUDE = ['site/screenshots/*', 'docs/_tools/*.pyc']

README = """# SOUL: complete package

Start with **docs/00-START-HERE.md**. It explains what SOUL is, the state of every part, and a map of every file.

- docs/01-BOM.md + docs/BOM.csv: bill of materials (P0 prototype + Founders 00)
- docs/02-MANUFACTURING.md: which file goes to which supplier, finishes, assembly, QC
- docs/03-SOFTWARE.md: firmware, AI service, SoulOS prototype, landing page (build/run/test)
- docs/04-COMPLIANCE.md · docs/05-LAUNCH-PLAN.md · docs/06-SUPPLIERS.md

Folders:
- firmware/ (PlatformIO)
- ai/ (Python)
- os/ (SoulOS web prototype + spec + architecture)
- site/ (landing page)
- prototip/ (DIY P0: STL, STEP, CAD sources)
- blueprints/final (SOUL M drawings) + older sheets
- renders/v8 (final design, size M; CGI, not photos) · brand/logo (The Glass O)
- research/ and investors/ (background)

Files left out for size are listed in SKIPPED.txt. They are in the original vault folder micul-smecher/.
Generated by docs/_tools/build_zip.py.
"""


def wanted(rel):
    return not any(fnmatch.fnmatch(rel, p) for p in EXCLUDE)


def files():
    seen = set()
    for folder, pats, rec in SPEC:
        base = os.path.join(ROOT, folder)
        if not os.path.isdir(base):
            yield ('MISSING', folder)
            continue
        walker = os.walk(base) if rec else [(base, [], os.listdir(base))]
        for d, dirs, fs in walker:
            dirs[:] = [x for x in dirs if x not in SKIP_DIRS]
            for f in sorted(fs):
                p = os.path.join(d, f)
                if not os.path.isfile(p) or f.endswith('.pyc') or f == '.DS_Store':
                    continue
                if not any(fnmatch.fnmatch(f, pat) for pat in pats):
                    continue
                rel = os.path.relpath(p, ROOT)
                if rel in seen or not wanted(rel):
                    continue
                if os.path.isfile(p + '.gz'):      # a gzipped twin exists (big STEP): ship only the .gz
                    continue
                seen.add(rel)
                yield ('FILE', rel)


def deflated_size(path):
    c = zlib.compressobj(6)
    n = 0
    with open(path, 'rb') as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b''):
            n += len(c.compress(chunk))
    return n + len(c.flush())


def main():
    os.makedirs(DIST, exist_ok=True)
    skipped, missing, count = [], [], 0
    tmp = ZIP + '.tmp'
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for kind, rel in files():
            if kind == 'MISSING':
                missing.append(rel)
                continue
            p = os.path.join(ROOT, rel)
            size = os.path.getsize(p)
            if size > MAX_DEFLATED and deflated_size(p) > MAX_DEFLATED:
                skipped.append((rel, size))
                continue
            z.write(p, PREFIX + rel)
            count += 1
        z.writestr(PREFIX + 'README.md', README)
        lines = ['Files NOT in this zip (too large; > %d MB even compressed). Find them in the vault folder micul-smecher/:' % (MAX_DEFLATED >> 20), '']
        lines += ['%8.1f MB  %s' % (s / 1e6, r) for r, s in skipped] or ['(none)']
        lines += ['', 'Also excluded by rule: a raw .step when a .step.gz twin exists (gunzip it), firmware/.pio (build output), ai caches and data/, prototip/cad/cache,',
                  'site/screenshots, os/screenshots, os/research, os/lang-mockups, cad/, media/, older renders (v4/v5), blueprints/src.']
        if missing:
            lines += ['', 'Folders expected but missing when the zip was built: ' + ', '.join(missing)]
        z.writestr(PREFIX + 'SKIPPED.txt', '\n'.join(lines) + '\n')
    os.replace(tmp, ZIP)
    print('files:', count, 'skipped:', len(skipped), 'missing:', missing)
    for r, s in skipped:
        print('  skipped %.1f MB %s' % (s / 1e6, r))
    print('zip: %s  %.1f MB' % (ZIP, os.path.getsize(ZIP) / 1e6))


if __name__ == '__main__':
    main()
