// GENERATED by tools/gen_eyes.js from ../eyes/eyes.js v2.1.0 and ../eyes/designs.json.
// Do not edit by hand: change the web engine / the collection and re-run the generator.
#pragma once
#include <stdint.h>

namespace suflet {
namespace eyes {

// ---- rig channels (eyes.js BASE, same order) ----
enum Ch : uint8_t {
  Ch_scale = 0,
  Ch_sx = 1,
  Ch_sy = 2,
  Ch_bob = 3,
  Ch_shift = 4,
  Ch_lift = 5,
  Ch_rot = 6,
  Ch_shake = 7,
  Ch_bounce = 8,
  Ch_blush = 9,
  Ch_tears = 10,
  Ch_cry = 11,
  Ch_q = 12,
  Ch_dots = 13,
  Ch_zzz = 14,
  Ch_spark = 15,
  Ch_check = 16,
  Ch_hearts = 17,
  Ch_bang = 18,
  Ch_spray = 19,
  Ch_listen = 20,
  Ch_bolt = 21,
  Ch_lidL = 22,
  Ch_lidR = 23,
  Ch_tiltL = 24,
  Ch_tiltR = 25,
  Ch_smileL = 26,
  Ch_smileR = 27,
  Ch_sizeL = 28,
  Ch_sizeR = 29,
  Ch_pupilL = 30,
  Ch_pupilR = 31,
  Ch_altL = 32,
  Ch_altR = 33,
  Ch_squeezeL = 34,
  Ch_squeezeR = 35,
  Ch_Count = 36
};
static constexpr float kBase[Ch_Count] = {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.06f, 0.06f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f};
static constexpr float kSpringK[Ch_Count] = {300.0f, 300.0f, 300.0f, 220.0f, 240.0f, 220.0f, 240.0f, 60.0f, 60.0f, 200.0f, 200.0f, 200.0f, 200.0f, 200.0f, 200.0f, 200.0f, 200.0f, 200.0f, 200.0f, 200.0f, 200.0f, 200.0f, 420.0f, 420.0f, 420.0f, 420.0f, 420.0f, 420.0f, 300.0f, 300.0f, 420.0f, 420.0f, 300.0f, 300.0f, 380.0f, 380.0f};
static constexpr float kSpringZ[Ch_Count] = {0.36f, 0.36f, 0.36f, 0.42f, 0.5f, 0.42f, 0.5f, 1.0f, 1.0f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.7f, 0.62f, 0.62f, 0.62f, 0.62f, 0.62f, 0.62f, 0.36f, 0.36f, 0.5f, 0.5f, 0.34f, 0.34f, 0.4f, 0.4f};
static const char* const kChNames[Ch_Count] = {"scale", "sx", "sy", "bob", "shift", "lift", "rot", "shake", "bounce", "blush", "tears", "cry", "q", "dots", "zzz", "spark", "check", "hearts", "bang", "spray", "listen", "bolt", "lidL", "lidR", "tiltL", "tiltR", "smileL", "smileR", "sizeL", "sizeR", "pupilL", "pupilR", "altL", "altR", "squeezeL", "squeezeR"};

enum class Shape : uint8_t { Egg, Squircle, Almond, Drop, Crescent };
enum class Pupil : uint8_t { Round, Slit, Plus, Star, Heart, Ring, Double, Pebble, Crescent, Diamond, Spiral, Battery, Level, None = 255 };
enum class GazeMode : uint8_t { Idle, Still, Spin, Rattle, Sway, Drift, Wobble, Scan, Keep = 255 };
namespace fx {
constexpr uint16_t Shimmer = 1u << 0;
constexpr uint16_t Rainbow = 1u << 1;
constexpr uint16_t Chrome = 1u << 2;
constexpr uint16_t Aurora = 1u << 3;
constexpr uint16_t Starfield = 1u << 4;
constexpr uint16_t Folk = 1u << 5;
constexpr uint16_t Glitter = 1u << 6;
constexpr uint16_t Outline = 1u << 7;
constexpr uint16_t Galaxy = 1u << 8;
constexpr uint16_t Halo = 1u << 9;
}  // namespace fx
enum class Rarity : uint8_t { Common, Uncommon, Rare, Epic, Legendary, Mythic, Count };
static constexpr double kRarityRate[] = {0.5, 0.25, 0.15, 0.07, 0.025, 0.005};
static const char* const kRarityName[] = {"Common", "Uncommon", "Rare", "Epic", "Legendary", "Mythic"};
static constexpr uint32_t kRarityColor[] = {0xC9C4B8, 0x5CFFB0, 0x3FA9FF, 0xB57BFF, 0xFFC23A, 0xFF4F9A};

struct Design {
  const char* id;
  const char* name;
  uint16_t num;
  Rarity rarity;
  Shape shape;
  float rx, ry, spacing, y, egg, lean, n, q, flick, dip;
  uint32_t white, whiteR;
  Pupil pupil;
  uint32_t pupilL, pupilR;
  float prx, pry, inset, travel;
  bool glint;
  uint32_t glintColor;
  float glintSize;
  uint16_t fx;
  float hue;
  uint32_t aurora[4];
  uint8_t nAurora;
  uint32_t folkBase, folkThread, glitter, halo;
};

static const Design kDesigns[120] = {
  {"original", "Original", 1, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF0C8, 0xFFF0C8, Pupil::Round, 0x2440FF, 0xFF5A1F,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"tangerine-dream", "Tangerine Dream", 2, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF9A3D, 0xFF9A3D, Pupil::Round, 0x1B2BFF, 0x6A2BFF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"bucharest-night", "Bucharest Night", 3, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x7FC8FF, 0x7FC8FF, Pupil::Round, 0xFFE14A, 0xFF3FA4,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"mint-condition", "Mint Condition", 4, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x3DFFC8, 0x3DFFC8, Pupil::Round, 0x6A2BFF, 0x6A2BFF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"lemonade-stand", "Lemonade Stand", 5, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF0FF2E, 0xF0FF2E, Pupil::Round, 0xFF2E5B, 0xFF2E5B,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"bubblegum-bus", "Bubblegum Bus", 6, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF8AD8, 0xFF8AD8, Pupil::Round, 0x2440FF, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"pistachio", "Pistachio", 7, Rarity::Common, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xA8FF3D, 0xA8FF3D, Pupil::Round, 0x7A2BFF, 0xFF2E5B,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"swimming-pool", "Swimming Pool", 8, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x2BD9FF, 0x2BD9FF, Pupil::Round, 0xFFE14A, 0xFFE14A,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"peach-crate", "Peach Crate", 9, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFB38A, 0xFFB38A, Pupil::Round, 0x2440FF, 0x00A35C,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"milk-tooth", "Milk Tooth", 10, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4F4F4, 0xF4F4F4, Pupil::Round, 0x111111, 0x111111,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"lilac-hour", "Lilac Hour", 11, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xC79BFF, 0xC79BFF, Pupil::Round, 0xFFE14A, 0x14E6FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"coral-snorkel", "Coral Snorkel", 12, Rarity::Common, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF6B6B, 0xFF6B6B, Pupil::Round, 0x14E6FF, 0x14E6FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"sunday-toast", "Sunday Toast", 13, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFD23A, 0xFFD23A, Pupil::Pebble, 0x5A2A10, 0x5A2A10,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"ski-lift", "Ski Lift", 14, Rarity::Common, Shape::Egg,
   0.13f, 0.215f, 0.158f, 0.0f, 0.06f, 0.1f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x7FC8FF, 0x7FC8FF, Pupil::Round, 0xFF5A1F, 0xFF5A1F,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"rose-petal", "Rose Petal", 15, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF9EBB, 0xFF9EBB, Pupil::Pebble, 0x5A0E5E, 0x5A0E5E,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"lime-soda", "Lime Soda", 16, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xA8FF3D, 0xA8FF3D, Pupil::Round, 0xFF1F8F, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"arcade-token", "Arcade Token", 17, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFD23A, 0xFFD23A, Pupil::Round, 0x6A2BFF, 0xFF2E5B,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"tram-41", "Tram 41", 18, Rarity::Common, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF4B4B, 0xFF4B4B, Pupil::Round, 0xFFE14A, 0xFFE14A,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"snow-day", "Snow Day", 19, Rarity::Common, Shape::Egg,
   0.13f, 0.215f, 0.158f, 0.0f, 0.06f, 0.1f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4F4F4, 0xF4F4F4, Pupil::Round, 0x2440FF, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"watermelon", "Watermelon", 20, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF6B8A, 0xFF6B8A, Pupil::Pebble, 0x0E7A3A, 0x0E7A3A,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"blue-raspberry", "Blue Raspberry", 21, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x5C8BFF, 0x5C8BFF, Pupil::Round, 0xFFE14A, 0xFF9A3D,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"matcha-latte", "Matcha Latte", 22, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xB8F07A, 0xB8F07A, Pupil::Round, 0x3A2A10, 0x3A2A10,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"highlighter", "Highlighter", 23, Rarity::Common, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xE8FF3A, 0xE8FF3A, Pupil::Round, 0xFF1F8F, 0xFF1F8F,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"flamingo-float", "Flamingo Float", 24, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF8AD8, 0xFF8AD8, Pupil::Round, 0x14E6FF, 0xFFE14A,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"apricot-jam", "Apricot Jam", 25, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF9A3D, 0xFF9A3D, Pupil::Pebble, 0x5A0E5E, 0x5A0E5E,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"glacier", "Glacier", 26, Rarity::Common, Shape::Egg,
   0.13f, 0.215f, 0.158f, 0.0f, 0.06f, 0.1f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xBDF4FF, 0xBDF4FF, Pupil::Round, 0x1B2BFF, 0x6A2BFF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"sherbet", "Sherbet", 27, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFC38A, 0xFFC38A, Pupil::Round, 0xFF1F8F, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"pea-pod", "Pea Pod", 28, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x7CFF8A, 0x7CFF8A, Pupil::Round, 0x111111, 0x111111,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"grape-soda", "Grape Soda", 29, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xB57BFF, 0xB57BFF, Pupil::Round, 0xF0FF2E, 0xF0FF2E,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"neon-taxi", "Neon Taxi", 30, Rarity::Common, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFD23A, 0xFFD23A, Pupil::Round, 0x111111, 0x111111,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"cotton-candy", "Cotton Candy", 31, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFB3E6, 0xFFB3E6, Pupil::Round, 0x2BD9FF, 0xB57BFF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"danube-blue", "Danube Blue", 32, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x3FA9FF, 0x3FA9FF, Pupil::Round, 0xFFF0C8, 0xFFF0C8,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"pumpkin-patch", "Pumpkin Patch", 33, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF7A1A, 0xFF7A1A, Pupil::Pebble, 0x1A1A1A, 0x1A1A1A,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"spring-onion", "Spring Onion", 34, Rarity::Common, Shape::Egg,
   0.13f, 0.215f, 0.158f, 0.0f, 0.06f, 0.1f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xC6FF5C, 0xC6FF5C, Pupil::Round, 0x2440FF, 0xFF2E5B,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"marshmallow", "Marshmallow", 35, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF6EC, 0xFFF6EC, Pupil::Pebble, 0xFF5A1F, 0xFF5A1F,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"fizzy-cola", "Fizzy Cola", 36, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF4B4B, 0xFF4B4B, Pupil::Round, 0xFFF0C8, 0x14E6FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"banana-boat", "Banana Boat", 37, Rarity::Common, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF27A, 0xFFF27A, Pupil::Round, 0x2440FF, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"morning-glory", "Morning Glory", 38, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x9FB4FF, 0x9FB4FF, Pupil::Round, 0xFF1F8F, 0xFF1F8F,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"kiwi-slice", "Kiwi Slice", 39, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xB8FF5C, 0xB8FF5C, Pupil::Round, 0x3A2A10, 0xFF2E5B,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"sea-breeze", "Sea Breeze", 40, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x5CFFE6, 0x5CFFE6, Pupil::Pebble, 0x1B2BFF, 0x1B2BFF,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"strawberry-milk", "Strawberry Milk", 41, Rarity::Common, Shape::Egg,
   0.13f, 0.215f, 0.158f, 0.0f, 0.06f, 0.1f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFB3C8, 0xFFB3C8, Pupil::Round, 0xD0102E, 0xD0102E,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"cucumber", "Cucumber", 42, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x9BFFB0, 0x9BFFB0, Pupil::Round, 0x7A2BFF, 0x7A2BFF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"traffic-cone", "Traffic Cone", 43, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF8A2A, 0xFF8A2A, Pupil::Round, 0x14E6FF, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"pastel-de-nata", "Pastel de Nata", 44, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFE08A, 0xFFE08A, Pupil::Pebble, 0x8A3A0A, 0x8A3A0A,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"polar-bear", "Polar Bear", 45, Rarity::Common, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4FAFF, 0xF4FAFF, Pupil::Round, 0x111111, 0x3FA9FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"sour-candy", "Sour Candy", 46, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xD6FF2E, 0xD6FF2E, Pupil::Round, 0xFF2E5B, 0x7A2BFF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"blue-hour", "Blue Hour", 47, Rarity::Common, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x7FA8FF, 0x7FA8FF, Pupil::Round, 0xFFF0C8, 0xFFE14A,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"hot-chocolate", "Hot Chocolate", 48, Rarity::Common, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFC9A0, 0xFFC9A0, Pupil::Round, 0x4A1E08, 0x4A1E08,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"cat-cafe", "Cat Caf\xc3""\xa9""", 49, Rarity::Uncommon, Shape::Almond,
   0.185f, 0.15f, 0.205f, 0.01f, 0.09f, 0.05f, 3.4f, 0.55f, 0.2f, 0.5f,
   0xF0FF2E, 0xF0FF2E, Pupil::Slit, 0x111111, 0x111111,
   0.5f, 0.62f, 0.05f, 0.4f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"alley-cat", "Alley Cat", 50, Rarity::Uncommon, Shape::Almond,
   0.185f, 0.15f, 0.205f, 0.01f, 0.09f, 0.05f, 3.4f, 0.55f, 0.2f, 0.5f,
   0xA8FF3D, 0xA8FF3D, Pupil::Slit, 0x111111, 0x111111,
   0.5f, 0.62f, 0.05f, 0.4f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"siamese", "Siamese", 51, Rarity::Uncommon, Shape::Almond,
   0.185f, 0.15f, 0.205f, 0.01f, 0.09f, 0.05f, 3.4f, 0.55f, 0.2f, 0.5f,
   0x7FC8FF, 0x7FC8FF, Pupil::Slit, 0x10184A, 0x10184A,
   0.5f, 0.62f, 0.05f, 0.4f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"tabby-orange", "Tabby Orange", 52, Rarity::Uncommon, Shape::Almond,
   0.185f, 0.15f, 0.205f, 0.01f, 0.09f, 0.05f, 3.4f, 0.55f, 0.2f, 0.5f,
   0xFF9A3D, 0xFF9A3D, Pupil::Slit, 0x2A0E00, 0x2A0E00,
   0.5f, 0.62f, 0.05f, 0.4f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"night-panther", "Night Panther", 53, Rarity::Uncommon, Shape::Almond,
   0.185f, 0.15f, 0.205f, 0.01f, 0.09f, 0.05f, 3.4f, 0.55f, 0.2f, 0.5f,
   0xC6FF5C, 0xC6FF5C, Pupil::Slit, 0x5A0E5E, 0x5A0E5E,
   0.5f, 0.62f, 0.05f, 0.4f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"dewdrop", "Dewdrop", 54, Rarity::Uncommon, Shape::Drop,
   0.165f, 0.195f, 0.19f, 0.01f, 0.09f, 0.24f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xBDF4FF, 0xBDF4FF, Pupil::Round, 0x2440FF, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"rain-boots", "Rain Boots", 55, Rarity::Uncommon, Shape::Drop,
   0.165f, 0.195f, 0.19f, 0.01f, 0.09f, 0.24f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFE14A, 0xFFE14A, Pupil::Round, 0xFF2E5B, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"teardrop-teal", "Teardrop Teal", 56, Rarity::Uncommon, Shape::Drop,
   0.165f, 0.195f, 0.19f, 0.01f, 0.09f, 0.24f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x2BFFE0, 0x2BFFE0, Pupil::Pebble, 0x6A2BFF, 0x6A2BFF,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"gumdrop", "Gumdrop", 57, Rarity::Uncommon, Shape::Drop,
   0.165f, 0.195f, 0.19f, 0.01f, 0.09f, 0.24f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF8AD8, 0xFF8AD8, Pupil::Round, 0xFFF0C8, 0xFFE14A,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"sugar-cube", "Sugar Cube", 58, Rarity::Uncommon, Shape::Squircle,
   0.155f, 0.172f, 0.185f, 0.005f, 0.09f, 0.06f, 3.6f, 0.5f, 0.18f, 0.5f,
   0xF4F4F4, 0xF4F4F4, Pupil::Round, 0xFF5A1F, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"pixel-pal", "Pixel Pal", 59, Rarity::Uncommon, Shape::Squircle,
   0.155f, 0.172f, 0.185f, 0.005f, 0.09f, 0.06f, 3.6f, 0.5f, 0.18f, 0.5f,
   0xA8FF3D, 0xA8FF3D, Pupil::Plus, 0x111111, 0x111111,
   0.4f, 0.4f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"tile-floor", "Tile Floor", 60, Rarity::Uncommon, Shape::Squircle,
   0.155f, 0.172f, 0.185f, 0.005f, 0.09f, 0.06f, 3.6f, 0.5f, 0.18f, 0.5f,
   0x3FA9FF, 0x3FA9FF, Pupil::Round, 0xFFE14A, 0xFFE14A,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"toaster", "Toaster", 61, Rarity::Uncommon, Shape::Squircle,
   0.155f, 0.172f, 0.185f, 0.005f, 0.09f, 0.06f, 3.6f, 0.5f, 0.18f, 0.5f,
   0xFFB38A, 0xFFB38A, Pupil::Ring, 0x2A2A2A, 0x2A2A2A,
   0.44f, 0.48f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"post-it", "Post-it", 62, Rarity::Uncommon, Shape::Squircle,
   0.155f, 0.172f, 0.185f, 0.005f, 0.09f, 0.06f, 3.6f, 0.5f, 0.18f, 0.5f,
   0xFFF27A, 0xFFF27A, Pupil::Pebble, 0xFF1F8F, 0x2440FF,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"half-moon-bay", "Half Moon Bay", 63, Rarity::Uncommon, Shape::Crescent,
   0.172f, 0.185f, 0.195f, 0.02f, 0.09f, 0.06f, 3.4f, 0.5f, 0.18f, 0.36f,
   0xFFF0C8, 0xFFF0C8, Pupil::Round, 0x2440FF, 0xFF5A1F,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"sleepy-lemon", "Sleepy Lemon", 64, Rarity::Uncommon, Shape::Crescent,
   0.172f, 0.185f, 0.195f, 0.02f, 0.09f, 0.06f, 3.4f, 0.5f, 0.18f, 0.36f,
   0xF0FF2E, 0xF0FF2E, Pupil::Round, 0x7A2BFF, 0x7A2BFF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"lagoon-lid", "Lagoon Lid", 65, Rarity::Uncommon, Shape::Crescent,
   0.172f, 0.185f, 0.195f, 0.02f, 0.09f, 0.06f, 3.4f, 0.5f, 0.18f, 0.36f,
   0x2BD9FF, 0x2BD9FF, Pupil::Round, 0xFF1F8F, 0xFF1F8F,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"bullseye", "Bullseye", 66, Rarity::Uncommon, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF0C8, 0xFFF0C8, Pupil::Ring, 0xFF2E5B, 0xFF2E5B,
   0.44f, 0.48f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"target-practice", "Target Practice", 67, Rarity::Uncommon, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4F4F4, 0xF4F4F4, Pupil::Ring, 0x2440FF, 0xFF2E5B,
   0.44f, 0.48f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"saturn-ring", "Saturn Ring", 68, Rarity::Uncommon, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFB38A, 0xFFB38A, Pupil::Ring, 0x6A2BFF, 0x6A2BFF,
   0.44f, 0.48f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"ladybug", "Ladybug", 69, Rarity::Uncommon, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF4B4B, 0xFF4B4B, Pupil::Double, 0x111111, 0x111111,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"domino", "Domino", 70, Rarity::Uncommon, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4F4F4, 0xF4F4F4, Pupil::Double, 0x111111, 0x111111,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"bubble-tea", "Bubble Tea", 71, Rarity::Uncommon, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFD6A8, 0xFFD6A8, Pupil::Double, 0x3A1E08, 0x3A1E08,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"moonbeam", "Moonbeam", 72, Rarity::Uncommon, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xBDF4FF, 0xBDF4FF, Pupil::Crescent, 0x2440FF, 0x2440FF,
   0.44f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"croissant", "Croissant", 73, Rarity::Uncommon, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFD23A, 0xFFD23A, Pupil::Crescent, 0x8A3A0A, 0x8A3A0A,
   0.44f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"midnight-snack", "Midnight Snack", 74, Rarity::Uncommon, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xC79BFF, 0xC79BFF, Pupil::Crescent, 0x111111, 0xFFE14A,
   0.44f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"odd-socks", "Odd Socks", 75, Rarity::Uncommon, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF0C8, 0x2BD9FF, Pupil::Round, 0x2440FF, 0xFF5A1F,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"two-scoops", "Two Scoops", 76, Rarity::Uncommon, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFB3E6, 0xB8F07A, Pupil::Pebble, 0x5A2A10, 0x5A2A10,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"split-decision", "Split Decision", 77, Rarity::Uncommon, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF0FF2E, 0xFF8AD8, Pupil::Round, 0x7A2BFF, 0x111111,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"pebble-beach", "Pebble Beach", 78, Rarity::Uncommon, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xBDB8AE, 0xBDB8AE, Pupil::Pebble, 0x2440FF, 0x2440FF,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"starstruck", "Starstruck", 79, Rarity::Rare, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF0C8, 0xFFF0C8, Pupil::Star, 0xFFB800, 0xFFB800,
   0.42f, 0.42f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"wish-upon", "Wish Upon", 80, Rarity::Rare, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x2440FF, 0x2440FF, Pupil::Star, 0xFFE14A, 0xFFE14A,
   0.42f, 0.42f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"shooting-star", "Shooting Star", 81, Rarity::Rare, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xB57BFF, 0xB57BFF, Pupil::Star, 0xF0FF2E, 0xFFFFFF,
   0.42f, 0.42f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"gold-medal", "Gold Medal", 82, Rarity::Rare, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF4B4B, 0xFF4B4B, Pupil::Star, 0xFFD23A, 0xFFD23A,
   0.42f, 0.42f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"smitten", "Smitten", 83, Rarity::Rare, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF0C8, 0xFFF0C8, Pupil::Heart, 0xFF2E63, 0xFF2E63,
   0.4f, 0.4f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"valentine-tram", "Valentine Tram", 84, Rarity::Rare, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF8AD8, 0xFF8AD8, Pupil::Heart, 0xD0102E, 0xD0102E,
   0.4f, 0.4f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"crush-soda", "Crush Soda", 85, Rarity::Rare, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x2BD9FF, 0x2BD9FF, Pupil::Heart, 0xFF2E63, 0xFF2E63,
   0.4f, 0.4f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"puppy-love", "Puppy Love", 86, Rarity::Rare, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF6EC, 0xFFF6EC, Pupil::Heart, 0xFF2E63, 0xB57BFF,
   0.4f, 0.4f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"crown-jewel", "Crown Jewel", 87, Rarity::Rare, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4F4F4, 0xF4F4F4, Pupil::Diamond, 0x6A2BFF, 0x14A0FF,
   0.38f, 0.48f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"card-shark", "Card Shark", 88, Rarity::Rare, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF4B4B, 0xFF4B4B, Pupil::Diamond, 0x111111, 0x111111,
   0.38f, 0.48f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"harlequin", "Harlequin", 89, Rarity::Rare, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFD23A, 0xFFD23A, Pupil::Diamond, 0xFF2E5B, 0x2440FF,
   0.38f, 0.48f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"first-aid", "First Aid", 90, Rarity::Rare, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4F4F4, 0xF4F4F4, Pupil::Plus, 0xFF2E5B, 0xFF2E5B,
   0.4f, 0.4f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"swiss-army", "Swiss Army", 91, Rarity::Rare, Shape::Squircle,
   0.155f, 0.172f, 0.185f, 0.005f, 0.09f, 0.06f, 3.6f, 0.5f, 0.18f, 0.5f,
   0xFF4B4B, 0xFF4B4B, Pupil::Plus, 0xFFFFFF, 0xFFFFFF,
   0.4f, 0.4f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"pharmacy-green", "Pharmacy Green", 92, Rarity::Rare, Shape::Squircle,
   0.155f, 0.172f, 0.185f, 0.005f, 0.09f, 0.06f, 3.6f, 0.5f, 0.18f, 0.5f,
   0x3DFFC8, 0x3DFFC8, Pupil::Plus, 0x0E7A3A, 0x0E7A3A,
   0.4f, 0.4f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"neon-sign", "Neon Sign", 93, Rarity::Rare, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF4FD8, 0xFF4FD8, Pupil::Round, 0xFF4FD8, 0x2BD9FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Outline, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"wireframe", "Wireframe", 94, Rarity::Rare, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x2BD9FF, 0x2BD9FF, Pupil::Pebble, 0x2BD9FF, 0x2BD9FF,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Outline, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"dragonfruit", "Dragonfruit", 95, Rarity::Rare, Shape::Almond,
   0.185f, 0.15f, 0.205f, 0.01f, 0.09f, 0.05f, 3.4f, 0.55f, 0.2f, 0.5f,
   0xFF4FD8, 0xA8FF3D, Pupil::Slit, 0xF4F4F4, 0xF4F4F4,
   0.5f, 0.62f, 0.05f, 0.4f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"eclipse", "Eclipse", 96, Rarity::Rare, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4F4F4, 0xFFD23A, Pupil::Crescent, 0x111111, 0x111111,
   0.44f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"hypno-toad", "Hypno Toad", 97, Rarity::Rare, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xA8FF3D, 0xA8FF3D, Pupil::Spiral, 0x5A0E5E, 0x5A0E5E,
   0.42f, 0.42f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"lollipop", "Lollipop", 98, Rarity::Rare, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFB3E6, 0xFFB3E6, Pupil::Spiral, 0xFF2E63, 0x2440FF,
   0.42f, 0.42f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   0, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"opal", "Opal", 99, Rarity::Epic, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xE6F6FF, 0xE6F6FF, Pupil::Round, 0x6A2BFF, 0xFF4FD8,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Shimmer, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"pearl-diver", "Pearl Diver", 100, Rarity::Epic, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4F0FF, 0xF4F0FF, Pupil::Pebble, 0x10184A, 0x10184A,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Shimmer, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"champagne", "Champagne", 101, Rarity::Epic, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFE6A8, 0xFFE6A8, Pupil::Star, 0x7A2BFF, 0x7A2BFF,
   0.42f, 0.42f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Shimmer | fx::Glitter, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFE6A8, 0xFFD23A},
  {"disco-ball", "Disco Ball", 102, Rarity::Epic, Shape::Squircle,
   0.155f, 0.172f, 0.185f, 0.005f, 0.09f, 0.06f, 3.6f, 0.5f, 0.18f, 0.5f,
   0xE8E8F0, 0xE8E8F0, Pupil::Diamond, 0xFF1F8F, 0x2BD9FF,
   0.38f, 0.48f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Glitter | fx::Shimmer, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"fairy-dust", "Fairy Dust", 103, Rarity::Epic, Shape::Drop,
   0.165f, 0.195f, 0.19f, 0.01f, 0.09f, 0.24f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFB3E6, 0xFFB3E6, Pupil::Round, 0x6A2BFF, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Glitter, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFE6F6, 0xFFD23A},
  {"firefly", "Firefly", 104, Rarity::Epic, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xC6FF5C, 0xC6FF5C, Pupil::Round, 0x111111, 0x111111,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Glitter, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xE8FF9A, 0xFFD23A},
  {"northern-lights", "Northern Lights", 105, Rarity::Epic, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x5CFFB0, 0x5CFFB0, Pupil::Round, 0x10184A, 0x10184A,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Aurora, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"tropical-sunset", "Tropical Sunset", 106, Rarity::Epic, Shape::Egg,
   0.19f, 0.142f, 0.205f, 0.01f, 0.03f, 0.06f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF9A3D, 0xFF9A3D, Pupil::Pebble, 0x2A0E3A, 0x2A0E3A,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Aurora, 0.0f, {0xFFD23A, 0xFF5A8A, 0xFF9A3D, 0xFF9A3D}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"laser-show", "Laser Show", 107, Rarity::Epic, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF1F8F, 0xFF1F8F, Pupil::Ring, 0x14E6FF, 0xF0FF2E,
   0.44f, 0.48f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Outline | fx::Glitter, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0x14E6FF, 0xFFD23A},
  {"vortex", "Vortex", 108, Rarity::Epic, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x14E6FF, 0x14E6FF, Pupil::Spiral, 0x111111, 0x111111,
   0.42f, 0.42f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Shimmer, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"ie-cobalt", "Ie Cobalt", 109, Rarity::Epic, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF0C8, 0xFFF0C8, Pupil::Round, 0x1F4FBF, 0x1F4FBF,
   0.56f, 0.56f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Folk, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x0A1A40, 0xFFFFFF, 0xFFD23A},
  {"ie-rosie", "Ie Ro\xc8""\x99""ie", 110, Rarity::Epic, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF4F4F4, 0xF4F4F4, Pupil::Round, 0xC8102E, 0xC8102E,
   0.56f, 0.56f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Folk, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"brushed-alu", "Brushed Alu", 111, Rarity::Legendary, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xD8DCE2, 0xD8DCE2, Pupil::Round, 0x111111, 0x2440FF,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Chrome | fx::Shimmer, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"rose-chrome", "Rose Chrome", 112, Rarity::Legendary, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xF2B8C0, 0xF2B8C0, Pupil::Pebble, 0x5A0E5E, 0x5A0E5E,
   0.44f, 0.46f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Chrome, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"midas-touch", "Midas Touch", 113, Rarity::Legendary, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFD23A, 0xFFD23A, Pupil::Star, 0x3A1E00, 0x3A1E00,
   0.42f, 0.42f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Chrome | fx::Glitter, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFE6A8, 0xFFD23A},
  {"prism-party", "Prism Party", 114, Rarity::Legendary, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFF6B6B, 0xFF6B6B, Pupil::Round, 0x111111, 0x111111,
   0.42f, 0.5f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Rainbow, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"night-over-sibiu", "Night Over Sibiu", 115, Rarity::Legendary, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF0C8, 0xFFF0C8, Pupil::Round, 0x0B1240, 0x0B1240,
   0.52f, 0.56f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Starfield | fx::Glitter, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"deep-field", "Deep Field", 116, Rarity::Legendary, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xB8C8FF, 0xB8C8FF, Pupil::Round, 0x05081F, 0x2A0640,
   0.5f, 0.56f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Starfield, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"altita", "Alti\xc8""\x9b""\xc4""\x83""", 117, Rarity::Legendary, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF0C8, 0xFFF0C8, Pupil::Round, 0xC8102E, 0xC8102E,
   0.56f, 0.56f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Folk | fx::Shimmer, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0xD9A21A, 0xFFFFFF, 0xFFD23A},
  {"genesis", "Genesis", 118, Rarity::Mythic, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFF0C8, 0xFFF0C8, Pupil::Round, 0x0B1240, 0x2A0A00,
   0.5f, 0.56f, 0.16f, 0.5f, true, 0xFFD23A, 1.25f,
   fx::Shimmer | fx::Halo | fx::Starfield, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"aurora-borealis", "Aurora Borealis", 119, Rarity::Mythic, Shape::Egg,
   0.163f, 0.2f, 0.19f, 0.005f, 0.09f, 0.13f, 3.4f, 0.5f, 0.18f, 0.5f,
   0x5CFFB0, 0x5CFFB0, Pupil::Round, 0x05081F, 0x05081F,
   0.5f, 0.55f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Aurora | fx::Starfield | fx::Glitter, 0.0f, {0x5CFFB0, 0x2BD9FF, 0xB57BFF, 0xFF6BD0}, 4,
   0xFFF6E6, 0x141414, 0xFFFFFF, 0xFFD23A},
  {"sanziana", "S\xc3""\xa2""nziana", 120, Rarity::Mythic, Shape::Egg,
   0.172f, 0.172f, 0.193f, 0.005f, 0.0f, 0.0f, 3.4f, 0.5f, 0.18f, 0.5f,
   0xFFE08A, 0xFFE08A, Pupil::Round, 0xC8102E, 0xC8102E,
   0.56f, 0.56f, 0.16f, 0.5f, true, 0xFFF6E2, 1.0f,
   fx::Chrome | fx::Folk | fx::Halo, 0.0f, {0x5CFFB0, 0x3FD9FF, 0xB07BFF, 0xB07BFF}, 3,
   0xFFF6E6, 0xD9A21A, 0xFFFFFF, 0xFFD23A},
};
static constexpr int kDesignCount = 120;

struct KV {
  uint8_t ch;
  float v;
};
struct Key {
  float t;
  const KV* snap;
  uint8_t nSnap;
  const KV* set;
  uint8_t nSet;
  const KV* kick;
  uint8_t nKick;
  Pupil alt;        // None = keep
  bool hasGaze;
  float gx, gy;
  GazeMode mode;    // Keep = keep
  float shakeF;     // 0 = keep
  uint8_t blink;    // 0 = none
};
struct MoodDef {
  const char* name;
  const char* label;
  float targets[Ch_Count];  // BASE merged with the mood set (eyes.js go())
  const KV* kick;
  uint8_t nKick;
  float anticD;             // 0 = no anticipation
  const KV* antic;
  uint8_t nAntic;
  bool anticHasGaze;
  float anticGx, anticGy;
  float gx, gy;             // base gaze
  GazeMode mode;
  Pupil alt;                // None = keep
  float shakeF;             // 20 when the mood has none
  float blinkSlow, blinkEvery;
  uint8_t blink;
  const Key* keys;
  uint8_t nKeys;
};
struct ReactionDef {
  const char* name;
  const char* label;
  float dur;
  const Key* keys;
  uint8_t nKeys;
};

static const KV kKv0[] = {{Ch_bob, -0.5f}, {Ch_sy, 2.4f}};
static const KV kKv1[] = {{Ch_sy, 0.88f}, {Ch_bob, 0.012f}, {Ch_scale, 0.98f}};
static const KV kKv2[] = {{Ch_scale, 3.0f}, {Ch_sy, 2.2f}};
static const KV kKv3[] = {{Ch_sy, 0.86f}, {Ch_scale, 0.94f}, {Ch_bob, 0.014f}};
static const KV kKv4[] = {{Ch_altL, 5.0f}, {Ch_altR, 5.0f}};
static const KV kKv5[] = {{Ch_pupilL, 0.0f}, {Ch_pupilR, 0.0f}, {Ch_scale, 0.96f}};
static const KV kKv6[] = {{Ch_shift, 0.4f}};
static const KV kKv7[] = {{Ch_shift, -0.012f}};
static const KV kKv8[] = {{Ch_bob, 0.3f}};
static const KV kKv9[] = {{Ch_sy, 1.04f}};
static const KV kKv10[] = {{Ch_sx, 2.0f}};
static const KV kKv11[] = {{Ch_sy, 1.05f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}};
static const KV kKv12[] = {{Ch_rot, 1.2f}};
static const Key kKeys13[] = {
    {0.0f, nullptr, 0, nullptr, 0, kKv12, 1, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
};
static const KV kKv14[] = {{Ch_lift, 0.01f}};
static const KV kKv15[] = {{Ch_altL, 4.0f}, {Ch_altR, 4.0f}, {Ch_sy, 2.0f}};
static const KV kKv16[] = {{Ch_sy, 0.86f}};
static const KV kKv17[] = {{Ch_rot, 1.0f}};
static const KV kKv18[] = {{Ch_lidL, 0.18f}, {Ch_lidR, 0.18f}, {Ch_tiltL, 0.2f}, {Ch_tiltR, 0.2f}};
static const KV kKv19[] = {{Ch_lidL, 0.32f}, {Ch_lidR, 0.32f}, {Ch_tiltL, 0.36f}, {Ch_tiltR, 0.36f}};
static const KV kKv20[] = {{Ch_lidL, 0.42f}, {Ch_lidR, 0.42f}, {Ch_tiltL, 0.46f}, {Ch_tiltR, 0.46f}, {Ch_smileL, 0.32f}, {Ch_smileR, 0.32f}};
static const Key kKeys21[] = {
    {0.2f, nullptr, 0, kKv18, 4, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.8f, nullptr, 0, kKv19, 4, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {1.5f, nullptr, 0, kKv20, 6, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
};
static const KV kKv22[] = {{Ch_altL, 3.0f}, {Ch_altR, 3.0f}};
static const KV kKv23[] = {{Ch_sy, 0.86f}};
static const KV kKv24[] = {{Ch_smileL, 0.86f}, {Ch_smileR, 0.86f}, {Ch_pupilL, 0.0f}, {Ch_pupilR, 0.0f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}, {Ch_tiltL, 0.0f}, {Ch_tiltR, 0.0f}, {Ch_sy, 1.0f}, {Ch_bounce, 1.0f}, {Ch_shake, 0.004f}};
static const KV kKv25[] = {{Ch_sy, 2.5f}};
static const KV kKv26[] = {{Ch_bounce, 0.0f}, {Ch_shake, 0.0f}};
static const Key kKeys27[] = {
    {0.0f, nullptr, 0, kKv23, 1, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.08f, nullptr, 0, kKv24, 11, kKv25, 1, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 9.0f, 0},
    {1.45f, nullptr, 0, kKv26, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
};
static const KV kKv28[] = {{Ch_sy, 0.94f}};
static const KV kKv29[] = {{Ch_sy, 1.0f}, {Ch_smileL, 0.98f}, {Ch_smileR, 0.26f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.06f}, {Ch_pupilL, 0.0f}, {Ch_pupilR, 1.0f}, {Ch_shift, 0.012f}, {Ch_rot, -0.04f}};
static const KV kKv30[] = {{Ch_bob, -0.3f}};
static const KV kKv31[] = {{Ch_smileL, 0.0f}, {Ch_smileR, 0.0f}, {Ch_shift, 0.0f}, {Ch_rot, 0.0f}, {Ch_pupilL, 1.0f}, {Ch_pupilR, 1.0f}};
static const Key kKeys32[] = {
    {0.0f, nullptr, 0, kKv28, 1, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.07f, nullptr, 0, kKv29, 9, kKv30, 1, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.8f, nullptr, 0, kKv31, 6, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
};
static const KV kKv33[] = {{Ch_sy, 0.8f}, {Ch_scale, 0.95f}};
static const KV kKv34[] = {{Ch_sy, 1.1f}, {Ch_scale, 1.18f}, {Ch_pupilL, 0.2f}, {Ch_pupilR, 0.2f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}, {Ch_tiltL, 0.0f}, {Ch_tiltR, 0.0f}, {Ch_lift, -0.03f}, {Ch_shake, 0.004f}, {Ch_bang, 1.0f}};
static const KV kKv35[] = {{Ch_scale, 4.0f}, {Ch_lift, -0.6f}};
static const KV kKv36[] = {{Ch_shake, 0.0f}, {Ch_bang, 0.0f}};
static const Key kKeys37[] = {
    {0.0f, nullptr, 0, kKv33, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.07f, nullptr, 0, kKv34, 11, kKv35, 2, Pupil::None, true, 0.0f, 0.0f, GazeMode::Still, 30.0f, 0},
    {1.05f, nullptr, 0, kKv36, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
};
static const KV kKv38[] = {{Ch_sy, 1.06f}, {Ch_lift, -0.012f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}, {Ch_tiltL, 0.0f}, {Ch_tiltR, 0.0f}, {Ch_pupilL, 0.9f}, {Ch_pupilR, 0.9f}};
static const KV kKv39[] = {{Ch_sy, 1.12f}, {Ch_lift, -0.022f}, {Ch_smileL, 0.2f}, {Ch_smileR, 0.2f}};
static const KV kKv40[] = {{Ch_squeezeL, 1.0f}, {Ch_squeezeR, 1.0f}, {Ch_smileL, 0.0f}, {Ch_smileR, 0.0f}, {Ch_sy, 0.9f}, {Ch_lift, 0.01f}};
static const KV kKv41[] = {{Ch_lift, 0.0f}, {Ch_sy, 1.0f}, {Ch_spray, 1.0f}, {Ch_shake, 0.016f}};
static const KV kKv42[] = {{Ch_scale, 3.5f}, {Ch_lift, 0.5f}};
static const KV kKv43[] = {{Ch_squeezeL, 0.0f}, {Ch_squeezeR, 0.0f}, {Ch_shake, 0.0f}, {Ch_spray, 0.0f}, {Ch_pupilL, 1.0f}, {Ch_pupilR, 1.0f}};
static const Key kKeys44[] = {
    {0.0f, nullptr, 0, kKv38, 8, nullptr, 0, Pupil::None, true, 0.0f, -0.55f, GazeMode::Still, 0.0f, 0},
    {0.32f, nullptr, 0, kKv39, 4, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.62f, nullptr, 0, kKv40, 6, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.8f, nullptr, 0, kKv41, 4, kKv42, 2, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 14.0f, 0},
    {1.2f, nullptr, 0, kKv43, 6, nullptr, 0, Pupil::None, true, 0.0f, 0.0f, GazeMode::Idle, 0.0f, 2},
};
static const KV kKv45[] = {{Ch_shake, 0.03f}, {Ch_pupilL, 0.45f}, {Ch_pupilR, 0.45f}, {Ch_scale, 1.1f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}, {Ch_tiltL, 0.0f}, {Ch_tiltR, 0.0f}, {Ch_bang, 1.0f}};
static const KV kKv46[] = {{Ch_scale, 3.0f}};
static const KV kKv47[] = {{Ch_shake, 0.0f}, {Ch_bang, 0.0f}, {Ch_altL, 1.0f}, {Ch_altR, 1.0f}, {Ch_pupilL, 0.0f}, {Ch_pupilR, 0.0f}};
static const KV kKv48[] = {{Ch_altL, 0.0f}, {Ch_altR, 0.0f}, {Ch_pupilL, 1.0f}, {Ch_pupilR, 1.0f}, {Ch_scale, 1.0f}};
static const Key kKeys49[] = {
    {0.0f, nullptr, 0, kKv45, 9, kKv46, 1, Pupil::None, false, 0.0f, 0.0f, GazeMode::Rattle, 17.0f, 0},
    {0.65f, nullptr, 0, kKv47, 6, nullptr, 0, Pupil::Spiral, false, 0.0f, 0.0f, GazeMode::Spin, 0.0f, 0},
    {1.35f, nullptr, 0, kKv48, 5, nullptr, 0, Pupil::None, true, 0.0f, 0.0f, GazeMode::Idle, 0.0f, 2},
};
static const KV kKv50[] = {{Ch_sy, 0.9f}};
static const KV kKv51[] = {{Ch_sy, 1.0f}, {Ch_smileL, 0.42f}, {Ch_smileR, 0.42f}, {Ch_pupilL, 0.6f}, {Ch_pupilR, 0.6f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}, {Ch_tiltL, 0.0f}, {Ch_tiltR, 0.0f}, {Ch_check, 1.0f}};
static const KV kKv52[] = {{Ch_scale, 2.6f}, {Ch_bob, -0.3f}};
static const KV kKv53[] = {{Ch_check, 0.0f}};
static const Key kKeys54[] = {
    {0.0f, nullptr, 0, kKv50, 1, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.08f, nullptr, 0, kKv51, 10, kKv52, 2, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {1.35f, nullptr, 0, kKv53, 1, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
};
static const KV kKv55[] = {{Ch_scale, 0.05f}, {Ch_lidL, 0.97f}, {Ch_lidR, 0.97f}};
static const KV kKv56[] = {{Ch_scale, 0.05f}, {Ch_lidL, 0.97f}, {Ch_lidR, 0.97f}};
static const KV kKv57[] = {{Ch_scale, 1.0f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}, {Ch_tiltL, 0.0f}, {Ch_tiltR, 0.0f}};
static const KV kKv58[] = {{Ch_scale, 3.0f}, {Ch_sy, 2.5f}};
static const KV kKv59[] = {{Ch_smileL, 0.3f}, {Ch_smileR, 0.3f}};
static const KV kKv60[] = {{Ch_smileL, 0.0f}, {Ch_smileR, 0.0f}};
static const Key kKeys61[] = {
    {0.0f, kKv55, 3, kKv56, 3, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.12f, nullptr, 0, kKv57, 5, kKv58, 2, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.75f, nullptr, 0, nullptr, 0, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 2},
    {0.95f, nullptr, 0, kKv59, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {1.35f, nullptr, 0, kKv60, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
};
static const KV kKv62[] = {{Ch_smileL, 0.3f}, {Ch_smileR, 0.3f}};
static const KV kKv63[] = {{Ch_smileL, 0.0f}, {Ch_smileR, 0.0f}, {Ch_scale, 0.32f}, {Ch_sy, 0.8f}, {Ch_pupilL, 0.0f}, {Ch_pupilR, 0.0f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}, {Ch_tiltL, 0.0f}, {Ch_tiltR, 0.0f}};
static const KV kKv64[] = {{Ch_scale, 0.0f}, {Ch_sy, 0.2f}};
static const KV kKv65[] = {{Ch_scale, 0.05f}, {Ch_lidL, 0.97f}, {Ch_lidR, 0.97f}};
static const KV kKv66[] = {{Ch_scale, 0.05f}, {Ch_sy, 1.0f}};
static const KV kKv67[] = {{Ch_scale, 1.0f}, {Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}, {Ch_pupilL, 1.0f}, {Ch_pupilR, 1.0f}};
static const KV kKv68[] = {{Ch_scale, 3.0f}};
static const Key kKeys69[] = {
    {0.0f, nullptr, 0, kKv62, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.5f, nullptr, 0, kKv63, 10, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {1.05f, nullptr, 0, kKv64, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {1.9f, kKv65, 3, kKv66, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {2.0f, nullptr, 0, kKv67, 5, kKv68, 1, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
};
static const KV kKv70[] = {{Ch_lidL, 0.95f}, {Ch_lidR, 0.95f}};
static const KV kKv71[] = {{Ch_lidL, 0.95f}, {Ch_lidR, 0.95f}, {Ch_tiltL, -0.1f}, {Ch_tiltR, -0.1f}, {Ch_bob, 0.03f}};
static const KV kKv72[] = {{Ch_lidL, 0.0f}, {Ch_lidR, 0.0f}, {Ch_tiltL, 0.0f}, {Ch_tiltR, 0.0f}, {Ch_sy, 1.26f}, {Ch_sx, 0.88f}, {Ch_lift, -0.035f}, {Ch_bob, 0.0f}};
static const KV kKv73[] = {{Ch_sy, 1.0f}, {Ch_sx, 1.0f}, {Ch_lift, 0.0f}};
static const KV kKv74[] = {{Ch_sy, -2.0f}};
static const KV kKv75[] = {{Ch_smileL, 0.25f}, {Ch_smileR, 0.25f}};
static const KV kKv76[] = {{Ch_smileL, 0.0f}, {Ch_smileR, 0.0f}};
static const Key kKeys77[] = {
    {0.0f, kKv70, 2, kKv71, 5, nullptr, 0, Pupil::None, true, 0.0f, 0.4f, GazeMode::Still, 0.0f, 0},
    {0.35f, nullptr, 0, kKv72, 8, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {0.85f, nullptr, 0, kKv73, 3, kKv74, 1, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {1.05f, nullptr, 0, nullptr, 0, nullptr, 0, Pupil::None, true, 0.0f, 0.0f, GazeMode::Idle, 0.0f, 2},
    {1.6f, nullptr, 0, kKv75, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
    {2.0f, nullptr, 0, kKv76, 2, nullptr, 0, Pupil::None, false, 0.0f, 0.0f, GazeMode::Keep, 0.0f, 0},
};

static const MoodDef kMoods[22] = {
  {"neutral", "Idle", {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.06f, 0.06f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Idle, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"happy", "Happy", {1.05f, 1.0f, 1.0f, 0.012f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.8f, 0.8f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, kKv0, 2, 0.09f, kKv1, 3, false, 0.0f, 0.0f, 0.0f, -0.3f, GazeMode::Idle, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"surprised", "Surprised", {1.12f, 1.0f, 1.07f, -0.02f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.42f, 0.42f, 0.0f, 0.0f, 0.0f, 0.0f}, kKv2, 2, 0.1f, kKv3, 3, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Idle, Pupil::None, 20.0f, 1.0f, 2.0f, 1, nullptr, 0},
  {"sleepy", "Sleepy", {0.97f, 1.0f, 1.0f, 0.022f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.56f, 0.6f, -0.12f, -0.12f, 0.0f, 0.0f, 1.0f, 1.0f, 0.95f, 0.95f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.0f, 0.45f, GazeMode::Still, Pupil::None, 20.0f, 3.0f, 4.5f, 0, nullptr, 0},
  {"love", "Love", {1.03f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f}, kKv4, 2, 0.12f, kKv5, 3, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Still, Pupil::Heart, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"smirk", "\xc8""\x98""mecher", {1.0f, 1.0f, 1.0f, 0.0f, 0.03f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.3f, 0.0f, 0.3f, 0.0f, 0.36f, 0.0f, 1.0f, 1.06f, 0.9f, 0.9f, 0.0f, 0.0f, 0.0f, 0.0f}, kKv6, 1, 0.1f, kKv7, 1, true, -0.35f, 0.0f, 0.82f, 0.04f, GazeMode::Still, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"sad", "Sad", {1.0f, 1.0f, 0.95f, 0.024f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.24f, 0.24f, -0.34f, -0.34f, 0.0f, 0.0f, 1.0f, 1.0f, 1.12f, 1.12f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.0f, 0.4f, GazeMode::Wobble, Pupil::None, 20.0f, 1.6f, 2.0f, 0, nullptr, 0},
  {"cry", "Cry", {1.0f, 1.0f, 0.92f, 0.03f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.36f, 0.36f, -0.4f, -0.4f, 0.12f, 0.12f, 1.0f, 1.0f, 1.05f, 1.05f, 0.0f, 0.0f, 0.0f, 0.0f}, kKv8, 1, 0.12f, kKv9, 1, false, 0.0f, 0.0f, 0.0f, 0.35f, GazeMode::Wobble, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"angry", "Angry", {1.0f, 1.04f, 0.94f, 0.008f, 0.0f, 0.0f, 0.0f, 0.004f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.32f, 0.32f, 0.5f, 0.5f, 0.0f, 0.0f, 1.0f, 1.0f, 0.66f, 0.66f, 0.0f, 0.0f, 0.0f, 0.0f}, kKv10, 1, 0.08f, kKv11, 3, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Still, Pupil::None, 24.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"dizzy", "Dizzy", {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.06f, 0.06f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Spin, Pupil::Spiral, 20.0f, 1.0f, 2.0f, 0, kKeys13, 1},
  {"suspicious", "Suspicious", {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.4f, 0.4f, 0.12f, 0.12f, 0.24f, 0.24f, 1.0f, 1.0f, 0.82f, 0.82f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Sway, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"smug", "Smug", {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, -0.028f, -0.07f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.46f, 0.46f, -0.06f, -0.06f, 0.14f, 0.14f, 1.0f, 1.0f, 0.9f, 0.9f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.1f, kKv14, 1, false, 0.0f, 0.0f, 0.12f, -0.12f, GazeMode::Still, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"shy", "Shy", {1.0f, 1.0f, 1.0f, 0.0f, -0.02f, 0.0f, 0.05f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.16f, 0.16f, -0.14f, -0.14f, 0.0f, 0.0f, 0.95f, 0.95f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, -0.65f, 0.6f, GazeMode::Still, Pupil::None, 20.0f, 1.0f, 1.6f, 0, nullptr, 0},
  {"excited", "Excited", {1.06f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f}, kKv15, 3, 0.1f, kKv16, 1, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Still, Pupil::Star, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"thinking", "Thinking", {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.14f, 0.32f, 0.04f, -0.12f, 0.0f, 0.0f, 1.0f, 1.0f, 0.92f, 0.92f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.6f, -0.58f, GazeMode::Drift, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"listening", "Listening", {1.05f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Still, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"confused", "Confused", {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.11f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.22f, 0.0f, 0.22f, -0.1f, 0.0f, 0.0f, 0.88f, 1.12f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f}, kKv17, 1, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.2f, -0.3f, GazeMode::Still, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"bored", "Bored", {1.0f, 1.0f, 0.96f, 0.01f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.5f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.8f, 0.8f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, -0.35f, 0.22f, GazeMode::Still, Pupil::None, 20.0f, 2.6f, 3.0f, 0, nullptr, 0},
  {"plan", "Evil plan", {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.06f, 0.06f, 0.2f, 0.2f, 1.0f, 1.0f, 0.78f, 0.78f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, -0.8f, 0.12f, GazeMode::Still, Pupil::None, 20.0f, 1.0f, 2.0f, 0, kKeys21, 3},
  {"working", "Claude is working", {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.12f, 0.12f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.78f, 0.78f, 0.0f, 0.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Scan, Pupil::None, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
  {"hungry", "Low battery", {1.0f, 1.0f, 0.9f, 0.03f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.3f, 0.3f, -0.16f, -0.16f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Still, Pupil::Battery, 20.0f, 2.0f, 2.0f, 0, nullptr, 0},
  {"charging", "Charging", {1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.06f, 0.06f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f}, kKv22, 2, 0.0f, nullptr, 0, false, 0.0f, 0.0f, 0.0f, 0.0f, GazeMode::Still, Pupil::Level, 20.0f, 1.0f, 2.0f, 0, nullptr, 0},
};
static const ReactionDef kReactions[9] = {
  {"laugh", "Laugh", 1.9f, kKeys27, 3},
  {"wink", "Wink", 1.05f, kKeys32, 3},
  {"shocked", "Shocked", 1.5f, kKeys37, 3},
  {"sneeze", "Sneeze", 1.9f, kKeys44, 5},
  {"startled", "Shaken", 2.0f, kKeys49, 3},
  {"approve", "Approve", 1.7f, kKeys54, 3},
  {"hello", "Hello", 1.6f, kKeys61, 5},
  {"goodbye", "Goodbye", 2.6f, kKeys69, 5},
  {"wake", "Wake up", 2.3f, kKeys77, 6},
};
static constexpr int kMoodCount = 22;
static constexpr int kReactionCount = 9;
// Expression index: moods first (0..kMoodCount-1), then reactions.
enum Expr : int8_t {
  X_neutral = 0,
  X_happy = 1,
  X_surprised = 2,
  X_sleepy = 3,
  X_love = 4,
  X_smirk = 5,
  X_sad = 6,
  X_cry = 7,
  X_angry = 8,
  X_dizzy = 9,
  X_suspicious = 10,
  X_smug = 11,
  X_shy = 12,
  X_excited = 13,
  X_thinking = 14,
  X_listening = 15,
  X_confused = 16,
  X_bored = 17,
  X_plan = 18,
  X_working = 19,
  X_hungry = 20,
  X_charging = 21,
  X_laugh = 22,
  X_wink = 23,
  X_shocked = 24,
  X_sneeze = 25,
  X_startled = 26,
  X_approve = 27,
  X_hello = 28,
  X_goodbye = 29,
  X_wake = 30,
  X_Count = 31
};
static constexpr int8_t kRandomPool[] = {X_happy, X_laugh, X_wink, X_surprised, X_smirk, X_love, X_thinking, X_suspicious, X_smug, X_shy, X_excited, X_confused, X_approve, X_shocked, X_sneeze, X_bored, X_plan, X_sad, X_angry, X_dizzy, X_working, X_listening};

struct ScriptEv {
  float t;
  int8_t mood;  // -1 = none
  bool look;
  float lx, ly;
  uint8_t blink;
  float slow;
  bool hop;
};
static constexpr float kLoopSeconds = 15.0f;
static const ScriptEv kScript[] = {
    {0.0f, X_neutral, true, 0.0f, 0.0f, 0, 0.0f, false},
    {0.55f, -1, true, -0.75f, -0.1f, 0, 0.0f, false},
    {1.15f, -1, true, 0.7f, 0.2f, 1, 0.0f, false},
    {1.9f, -1, true, 0.05f, -0.05f, 0, 0.0f, false},
    {2.25f, -1, false, 0.0f, 0.0f, 0, 0.0f, true},
    {2.6f, -1, false, 0.0f, 0.0f, 2, 0.0f, false},
    {3.1f, X_happy, false, 0.0f, 0.0f, 0, 0.0f, false},
    {4.7f, X_neutral, false, 0.0f, 0.0f, 0, 0.0f, false},
    {4.85f, -1, true, -0.5f, 0.35f, 0, 0.0f, false},
    {5.35f, -1, true, 0.0f, 0.0f, 0, 0.0f, false},
    {5.6f, X_surprised, false, 0.0f, 0.0f, 0, 0.0f, false},
    {7.0f, X_neutral, false, 0.0f, 0.0f, 1, 0.0f, false},
    {7.45f, X_smirk, false, 0.0f, 0.0f, 0, 0.0f, false},
    {8.7f, -1, false, 0.0f, 0.0f, 1, 0.0f, false},
    {9.35f, X_neutral, false, 0.0f, 0.0f, 0, 0.0f, false},
    {9.6f, X_love, false, 0.0f, 0.0f, 0, 0.0f, false},
    {11.45f, X_neutral, false, 0.0f, 0.0f, 1, 0.0f, false},
    {11.8f, X_sleepy, false, 0.0f, 0.0f, 0, 0.0f, false},
    {12.9f, -1, false, 0.0f, 0.0f, 1, 3.0f, false},
    {14.2f, X_neutral, true, 0.0f, 0.0f, 0, 0.0f, false},
    {14.35f, -1, false, 0.0f, 0.0f, 2, 0.0f, false},
};

}  // namespace eyes
}  // namespace suflet
