// Bitmap fonts for Canvas::drawText, plus the small UTF-8 toolkit the text
// input needs. The glyph data is generated by tools/gen_font.py (Nunito, OFL)
// into FontData.h and lives in flash.
#pragma once
#include <stddef.h>
#include <stdint.h>

namespace suflet {

struct Glyph {
  uint16_t cp;     // code point
  uint16_t adv16;  // advance, 1/16 px
  uint32_t off;    // byte offset into Font::bits
  uint8_t w, h;    // bitmap size
  int8_t x, y;     // bitmap offset from the pen on the baseline (y down)
};

struct Font {
  const char* name;
  uint8_t px;       // nominal size
  int8_t ascent;    // above the baseline
  int8_t descent;   // below the baseline
  uint8_t lineH;    // suggested line pitch
  uint16_t count;
  const Glyph* glyphs;  // sorted by cp
  const uint8_t* bits;  // 4 bpp, rows padded to whole bytes

  // Glyph for a code point. Cedilla ş ţ map to the comma-below ș ț, and
  // anything missing falls back to '?' (never null for a real font).
  const Glyph* find(uint32_t cp) const;
  // 4-bit coverage (0..15) of pixel (x, y) inside glyph g.
  uint8_t cov(const Glyph& g, int x, int y) const {
    const uint8_t b = bits[g.off + y * ((g.w + 1) >> 1) + (x >> 1)];
    return (x & 1) ? (b & 0x0F) : (b >> 4);
  }
};

// The built-in sizes (tools/gen_font.py).
namespace fonts {
const Font& small();   // 22 px SemiBold: labels, suggestions, numerals
const Font& text();    // 26 px SemiBold: keys, the text field
const Font& large();   // 36 px Bold: callout, variant tray
const Font& digits();  // 88 px Bold, 0-9 and ':' only: time picker
}  // namespace fonts

enum class Align : uint8_t { Left, Center, Right };

// ---- UTF-8 -------------------------------------------------------------
namespace utf8 {
// Decode one code point at p (stops at end / NUL) and advance p. Invalid
// bytes decode to U+FFFD and advance by one, so loops always terminate.
uint32_t next(const char*& p, const char* end = nullptr);
// Append the UTF-8 encoding of cp to out (up to 4 bytes); returns the count.
int encode(uint32_t cp, char* out);
// Number of code points in s[0, n).
size_t count(const char* s, size_t n);
// Byte index of the start of the code point that ends at byte n.
size_t prevStart(const char* s, size_t n);
// ş ţ Ş Ţ (cedilla) -> ș ț Ș Ț (comma below): the only Romanian forms we emit.
uint32_t normalizeRo(uint32_t cp);
// Lower case for ASCII, Latin-1 and the Romanian letters.
uint32_t lower(uint32_t cp);
uint32_t upper(uint32_t cp);
// Base letter without diacritics (ă â -> a, î -> i, ș -> s, ț -> t, é -> e...).
uint32_t fold(uint32_t cp);
// Is it one of ă â î ș ț (either case)?
bool isRoDiacritic(uint32_t cp);
}  // namespace utf8

}  // namespace suflet
